<?php
/**
 * ReturnShipmentsV1Api
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ReturnShipmentsV1Api Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReturnShipmentsV1Api
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'returnShipmentsV1ListReturnShipmentsUsingGET' => [
            'application/json',
        ],
        'returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET' => [
            'application/json',
        ],
        'returnShipmentsV1ReturnShipmentUsingGET' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation returnShipmentsV1ListReturnShipmentsUsingGET
     *
     * Retrieve returnShipments.
     *
     * @param  \DateTime $datefrom ReturnShipments which are announced after this date or had an status update after this date will be returned for the partner which is determined from the authorization token. The date is considered as UTC. (required)
     * @param  int|null $limit The maximum number of returnShipments to be returned in each response. (optional, default to 25)
     * @param  string|null $next The cursor which points to the next returnShipment that should be queried. It is used to paginate the results. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ReturnShipmentListReturnShipmentsV1|\OpenAPI\Client\Model\BadRequestReturnShipmentsV1|mixed|\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentListReturnShipmentsV1
     */
    public function returnShipmentsV1ListReturnShipmentsUsingGET($datefrom, $limit = 25, $next = null, string $contentType = self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'][0])
    {
        list($response) = $this->returnShipmentsV1ListReturnShipmentsUsingGETWithHttpInfo($datefrom, $limit, $next, $contentType);
        return $response;
    }

    /**
     * Operation returnShipmentsV1ListReturnShipmentsUsingGETWithHttpInfo
     *
     * Retrieve returnShipments.
     *
     * @param  \DateTime $datefrom ReturnShipments which are announced after this date or had an status update after this date will be returned for the partner which is determined from the authorization token. The date is considered as UTC. (required)
     * @param  int|null $limit The maximum number of returnShipments to be returned in each response. (optional, default to 25)
     * @param  string|null $next The cursor which points to the next returnShipment that should be queried. It is used to paginate the results. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ReturnShipmentListReturnShipmentsV1|\OpenAPI\Client\Model\BadRequestReturnShipmentsV1|mixed|\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentListReturnShipmentsV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function returnShipmentsV1ListReturnShipmentsUsingGETWithHttpInfo($datefrom, $limit = 25, $next = null, string $contentType = self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'][0])
    {
        $request = $this->returnShipmentsV1ListReturnShipmentsUsingGETRequest($datefrom, $limit, $next, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ReturnShipmentListReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BadRequestReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentListReturnShipmentsV1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ReturnShipmentListReturnShipmentsV1',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ReturnShipmentListReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BadRequestReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentListReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation returnShipmentsV1ListReturnShipmentsUsingGETAsync
     *
     * Retrieve returnShipments.
     *
     * @param  \DateTime $datefrom ReturnShipments which are announced after this date or had an status update after this date will be returned for the partner which is determined from the authorization token. The date is considered as UTC. (required)
     * @param  int|null $limit The maximum number of returnShipments to be returned in each response. (optional, default to 25)
     * @param  string|null $next The cursor which points to the next returnShipment that should be queried. It is used to paginate the results. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function returnShipmentsV1ListReturnShipmentsUsingGETAsync($datefrom, $limit = 25, $next = null, string $contentType = self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'][0])
    {
        return $this->returnShipmentsV1ListReturnShipmentsUsingGETAsyncWithHttpInfo($datefrom, $limit, $next, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation returnShipmentsV1ListReturnShipmentsUsingGETAsyncWithHttpInfo
     *
     * Retrieve returnShipments.
     *
     * @param  \DateTime $datefrom ReturnShipments which are announced after this date or had an status update after this date will be returned for the partner which is determined from the authorization token. The date is considered as UTC. (required)
     * @param  int|null $limit The maximum number of returnShipments to be returned in each response. (optional, default to 25)
     * @param  string|null $next The cursor which points to the next returnShipment that should be queried. It is used to paginate the results. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function returnShipmentsV1ListReturnShipmentsUsingGETAsyncWithHttpInfo($datefrom, $limit = 25, $next = null, string $contentType = self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ReturnShipmentListReturnShipmentsV1';
        $request = $this->returnShipmentsV1ListReturnShipmentsUsingGETRequest($datefrom, $limit, $next, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'returnShipmentsV1ListReturnShipmentsUsingGET'
     *
     * @param  \DateTime $datefrom ReturnShipments which are announced after this date or had an status update after this date will be returned for the partner which is determined from the authorization token. The date is considered as UTC. (required)
     * @param  int|null $limit The maximum number of returnShipments to be returned in each response. (optional, default to 25)
     * @param  string|null $next The cursor which points to the next returnShipment that should be queried. It is used to paginate the results. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function returnShipmentsV1ListReturnShipmentsUsingGETRequest($datefrom, $limit = 25, $next = null, string $contentType = self::contentTypes['returnShipmentsV1ListReturnShipmentsUsingGET'][0])
    {

        // verify the required parameter 'datefrom' is set
        if ($datefrom === null || (is_array($datefrom) && count($datefrom) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $datefrom when calling returnShipmentsV1ListReturnShipmentsUsingGET'
            );
        }

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ReturnShipmentsV1Api.returnShipmentsV1ListReturnShipmentsUsingGET, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ReturnShipmentsV1Api.returnShipmentsV1ListReturnShipmentsUsingGET, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/v1/return-shipments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $datefrom,
            'datefrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $next,
            'next', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET
     *
     * Retrieve returnShipment by carrier and tracking number.
     *
     * @param  string $carrier The carrier of the returnShipment. (required)
     * @param  string $tracking_number The tracking number of the returnShipment assigned by the carrier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1|\OpenAPI\Client\Model\BadRequestReturnShipmentsV1|mixed|\OpenAPI\Client\Model\ForbiddenGetReturnShipmentByTrackingNumberReturnShipmentsV1|\OpenAPI\Client\Model\NotFoundGetReturnShipmentByTrackingNumberReturnShipmentsV1|\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentByTrackingNumberReturnShipmentsV1
     */
    public function returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET($carrier, $tracking_number, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'][0])
    {
        list($response) = $this->returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETWithHttpInfo($carrier, $tracking_number, $contentType);
        return $response;
    }

    /**
     * Operation returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETWithHttpInfo
     *
     * Retrieve returnShipment by carrier and tracking number.
     *
     * @param  string $carrier The carrier of the returnShipment. (required)
     * @param  string $tracking_number The tracking number of the returnShipment assigned by the carrier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1|\OpenAPI\Client\Model\BadRequestReturnShipmentsV1|mixed|\OpenAPI\Client\Model\ForbiddenGetReturnShipmentByTrackingNumberReturnShipmentsV1|\OpenAPI\Client\Model\NotFoundGetReturnShipmentByTrackingNumberReturnShipmentsV1|\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentByTrackingNumberReturnShipmentsV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETWithHttpInfo($carrier, $tracking_number, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'][0])
    {
        $request = $this->returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETRequest($carrier, $tracking_number, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BadRequestReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ForbiddenGetReturnShipmentByTrackingNumberReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\NotFoundGetReturnShipmentByTrackingNumberReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentByTrackingNumberReturnShipmentsV1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BadRequestReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ForbiddenGetReturnShipmentByTrackingNumberReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\NotFoundGetReturnShipmentByTrackingNumberReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentByTrackingNumberReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETAsync
     *
     * Retrieve returnShipment by carrier and tracking number.
     *
     * @param  string $carrier The carrier of the returnShipment. (required)
     * @param  string $tracking_number The tracking number of the returnShipment assigned by the carrier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETAsync($carrier, $tracking_number, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'][0])
    {
        return $this->returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETAsyncWithHttpInfo($carrier, $tracking_number, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETAsyncWithHttpInfo
     *
     * Retrieve returnShipment by carrier and tracking number.
     *
     * @param  string $carrier The carrier of the returnShipment. (required)
     * @param  string $tracking_number The tracking number of the returnShipment assigned by the carrier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETAsyncWithHttpInfo($carrier, $tracking_number, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1';
        $request = $this->returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETRequest($carrier, $tracking_number, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'
     *
     * @param  string $carrier The carrier of the returnShipment. (required)
     * @param  string $tracking_number The tracking number of the returnShipment assigned by the carrier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGETRequest($carrier, $tracking_number, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'][0])
    {

        // verify the required parameter 'carrier' is set
        if ($carrier === null || (is_array($carrier) && count($carrier) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier when calling returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'
            );
        }

        // verify the required parameter 'tracking_number' is set
        if ($tracking_number === null || (is_array($tracking_number) && count($tracking_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tracking_number when calling returnShipmentsV1ReturnShipmentByCarrierAndTrackingNumberUsingGET'
            );
        }


        $resourcePath = '/v1/return-shipments/carriers/{carrier}/trackingnumbers/{trackingNumber}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($carrier !== null) {
            $resourcePath = str_replace(
                '{' . 'carrier' . '}',
                ObjectSerializer::toPathValue($carrier),
                $resourcePath
            );
        }
        // path params
        if ($tracking_number !== null) {
            $resourcePath = str_replace(
                '{' . 'trackingNumber' . '}',
                ObjectSerializer::toPathValue($tracking_number),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation returnShipmentsV1ReturnShipmentUsingGET
     *
     * Retrieve returnShipments by returnShipment ID.
     *
     * @param  string $return_shipment_id Internal return shipment identifier assigned by OTTO Market. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1|\OpenAPI\Client\Model\BadRequestReturnShipmentsV1|mixed|\OpenAPI\Client\Model\ForbiddenGetReturnShipmentByReturnShipmentIdReturnShipmentsV1|\OpenAPI\Client\Model\NotFoundGetReturnShipmentByReturnShipmentIdReturnShipmentsV1|\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentByReturnShipmentIdReturnShipmentsV1
     */
    public function returnShipmentsV1ReturnShipmentUsingGET($return_shipment_id, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'][0])
    {
        list($response) = $this->returnShipmentsV1ReturnShipmentUsingGETWithHttpInfo($return_shipment_id, $contentType);
        return $response;
    }

    /**
     * Operation returnShipmentsV1ReturnShipmentUsingGETWithHttpInfo
     *
     * Retrieve returnShipments by returnShipment ID.
     *
     * @param  string $return_shipment_id Internal return shipment identifier assigned by OTTO Market. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1|\OpenAPI\Client\Model\BadRequestReturnShipmentsV1|mixed|\OpenAPI\Client\Model\ForbiddenGetReturnShipmentByReturnShipmentIdReturnShipmentsV1|\OpenAPI\Client\Model\NotFoundGetReturnShipmentByReturnShipmentIdReturnShipmentsV1|\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentByReturnShipmentIdReturnShipmentsV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function returnShipmentsV1ReturnShipmentUsingGETWithHttpInfo($return_shipment_id, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'][0])
    {
        $request = $this->returnShipmentsV1ReturnShipmentUsingGETRequest($return_shipment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BadRequestReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ForbiddenGetReturnShipmentByReturnShipmentIdReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\NotFoundGetReturnShipmentByReturnShipmentIdReturnShipmentsV1',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentByReturnShipmentIdReturnShipmentsV1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BadRequestReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ForbiddenGetReturnShipmentByReturnShipmentIdReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\NotFoundGetReturnShipmentByReturnShipmentIdReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InternalServerErrorGetReturnShipmentByReturnShipmentIdReturnShipmentsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation returnShipmentsV1ReturnShipmentUsingGETAsync
     *
     * Retrieve returnShipments by returnShipment ID.
     *
     * @param  string $return_shipment_id Internal return shipment identifier assigned by OTTO Market. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function returnShipmentsV1ReturnShipmentUsingGETAsync($return_shipment_id, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'][0])
    {
        return $this->returnShipmentsV1ReturnShipmentUsingGETAsyncWithHttpInfo($return_shipment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation returnShipmentsV1ReturnShipmentUsingGETAsyncWithHttpInfo
     *
     * Retrieve returnShipments by returnShipment ID.
     *
     * @param  string $return_shipment_id Internal return shipment identifier assigned by OTTO Market. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function returnShipmentsV1ReturnShipmentUsingGETAsyncWithHttpInfo($return_shipment_id, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ReturnShipmentReturnShipmentsV1';
        $request = $this->returnShipmentsV1ReturnShipmentUsingGETRequest($return_shipment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'returnShipmentsV1ReturnShipmentUsingGET'
     *
     * @param  string $return_shipment_id Internal return shipment identifier assigned by OTTO Market. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function returnShipmentsV1ReturnShipmentUsingGETRequest($return_shipment_id, string $contentType = self::contentTypes['returnShipmentsV1ReturnShipmentUsingGET'][0])
    {

        // verify the required parameter 'return_shipment_id' is set
        if ($return_shipment_id === null || (is_array($return_shipment_id) && count($return_shipment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $return_shipment_id when calling returnShipmentsV1ReturnShipmentUsingGET'
            );
        }


        $resourcePath = '/v1/return-shipments/{returnShipmentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($return_shipment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'returnShipmentId' . '}',
                ObjectSerializer::toPathValue($return_shipment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
