{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "OTTO Market API",
    "x-logo": {
      "url": "https://nonlive.portal.otto.market/static/assets/images/otto_market_logo_borderless.svg",
      "backgroundColor": "#ffffff"
    }
  },
  "servers": [
    {
      "url": "https://api.otto.market",
      "description": "Live Server"
    }
  ],
  "paths": {
    "/v4/products": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "The total number of results could be limited by specifying query parameters. Generally the resulting product variations will be paginated. The default page length is 100 product variations per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V4__getPartnerProducts",
        "summary": "Read product variations",
        "tags": [
          "Products V4"
        ]
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns a process-id to query results. The limit for the number of product variations in one request is 500.",
        "operationId": "Products-V4__createOrUpdateProductVariations",
        "summary": "Create or update product variations",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/active-status": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "The total number of results could be limited by specifying query parameters. Generally the resulting active status values will be paginated. The default page length is 100 active status entries per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V4__getActiveStatus",
        "summary": "Read active status",
        "tags": [
          "Products V4"
        ]
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns a process-id to query results. The limit for the number of product active statuses in one request is 500.",
        "operationId": "Products-V4__updateActiveStatus",
        "summary": "Update active status",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/brands": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Read the list of brands that are known on the Otto market place. The list of brands will be paginated. Brands consist of a name, a brand Id, a (link to a) logo and a boolean useable that lets you know wheter you are allowed to set up variants with this brand on the Otto Marketplace. The default page length is 100 entries per response, the page size upper limit is 1000. The links specified in the result can be used to page through the total result space. Note that there wi[...]",
        "operationId": "Products-V4__getBrands",
        "summary": "List of allowed brands",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/categories": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns product categories and associated attributes of the OTTO market place. The total number of results could be limited by specifying query parameters. Generally the resulting product categories values will be paginated. The default page length is 100 product categories per response, the page size limit is 2000. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V4__getCategoryGroups",
        "summary": "Read product categories",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/content-changes": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Read the content changes for all your product variations within a specific time period. You can also use this endpoint to read the content changes for more than one variation or if the sku value contains slash ('/') or dot ('.') characters, so that you cannot use the other endpoint with one dedicated sku value in the path. The resulting content changes will be paginated. The default page length is 100 entries per response, which also is the page size upper limit. The link[...]",
        "operationId": "Products-V4__getContentChanges2",
        "summary": "Read content changes within time period",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/marketplace-status": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "The total number of results could be limited by specifying query parameters. Generally the resulting marketplace status will be paginated. The default page length is 100 product variations per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V4__getMarketPlaceStatusList",
        "summary": "Read marketplace status of product variations",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/prices": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Read your product variations prices. The total number of results could be limited by specifying query parameters. Generally the resulting product variations will be paginated. The default page length is 100 product variations per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V4__getProductVariationPrices",
        "summary": "Read product variations prices",
        "tags": [
          "Products V4"
        ]
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Update your product variation prices and get a process-id to query results. The limit for the number of product variation prices in one request is 500.",
        "operationId": "Products-V4__updateProductVariationPrices",
        "summary": "Update product variation prices",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/update-tasks/{processUuid}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "The response will contain the links for the different parts of the result: products successfully created or updated, products with failures, products which did not contain any changes compared to the last sent version.",
        "operationId": "Products-V4__progressByProcessId",
        "summary": "Request the results of a product data delivery",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/update-tasks/{processUuid}/failed": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Request the failed products of the product data delivery with the linked processUuid. The response will contain a list of failed products with associated error details.",
        "operationId": "Products-V4__failedByProcessId",
        "summary": "List failed products of a product data delivery",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/update-tasks/{processUuid}/succeeded": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Request the succeeded products of the product data delivery with the linked processUuid. The response will contain a list of successfully delivered products.",
        "operationId": "Products-V4__succeededByProcessId",
        "summary": "List succeeded products of a product data delivery",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/update-tasks/{processUuid}/unchanged": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Request the unchanged products of the product data delivery with the linked processUuid. The response will contain a list of unchanged products.",
        "operationId": "Products-V4__unchangedByProcessId",
        "summary": "List unchanged products of a product data delivery",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/{sku}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns a single product variation by SKU.",
        "operationId": "Products-V4__getProductVariation",
        "summary": "Read a single product variation",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/{sku}/active-status": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns active status of the requested product variation by SKU.",
        "operationId": "Products-V4__getVariationActiveStatus",
        "summary": "Read the active status of a single product variation",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/{sku}/content-changes": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns the content changes info for a single product variation within a specific time period. The resulting content changes will be paginated. The default page length is 100 entries per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V4__getContentChanges",
        "summary": "Read content changes for a single product variation",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/{sku}/marketplace-status": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns marketplace status for a single product variation by SKU.",
        "operationId": "Products-V4__getMarketPlaceStatus",
        "summary": "Read marketplace status for a single product variation",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v4/products/{sku}/prices": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Read the price data of a single product variation.",
        "operationId": "Products-V4__getProductVariationPrice",
        "summary": "Read a single product variation price",
        "tags": [
          "Products V4"
        ]
      }
    },
    "/v5/products": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "The total number of results could be limited by specifying query parameters. Generally the resulting product variations will be paginated. The default page length is 100 product variations per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V5__getPartnerProducts",
        "summary": "Read product variations",
        "tags": [
          "Products V5"
        ]
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns a process-id to query results. The limit for the number of product variations in one request is 500.",
        "operationId": "Products-V5__createOrUpdateProductVariations",
        "summary": "Create or update product variations",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/active-status": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "The total number of results could be limited by specifying query parameters. Generally the resulting active status values will be paginated. The default page length is 100 active status entries per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V5__getActiveStatus",
        "summary": "Read active status",
        "tags": [
          "Products V5"
        ]
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns a process-id to query results. The limit for the number of product active statuses in one request is 500.",
        "operationId": "Products-V5__updateActiveStatus",
        "summary": "Update active status",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/brands": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Read the list of brands that are known on the Otto market place. The list of brands will be paginated. Brands consist of a name, a brand Id, a (link to a) logo and a boolean useable that lets you know wheter you are allowed to set up variants with this brand on the Otto Marketplace. The default page length is 100 entries per response, the page size upper limit is 1000. The links specified in the result can be used to page through the total result space. Note that there wi[...]",
        "operationId": "Products-V5__getBrands",
        "summary": "List of allowed brands",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/categories": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns product categories and associated attributes of the OTTO market place. The total number of results could be limited by specifying query parameters. Generally the resulting product categories values will be paginated. The default page length is 100 product categories per response, the page size limit is 2000. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V5__getCategoryGroups",
        "summary": "Read product categories",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/content-changes": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Read the content changes for all your product variations within a specific time period. You can also use this endpoint to read the content changes for more than one variation or if the sku value contains slash ('/') or dot ('.') characters, so that you cannot use the other endpoint with one dedicated sku value in the path. The resulting content changes will be paginated. The default page length is 100 entries per response, which also is the page size upper limit. The link[...]",
        "operationId": "Products-V5__getContentChanges2",
        "summary": "Read content changes within time period",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/marketplace-status": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "The total number of results could be limited by specifying query parameters. Generally the resulting marketplace status will be paginated. The default page length is 100 product variations per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V5__getMarketPlaceStatusList",
        "summary": "Read marketplace status of product variations",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/prices": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Read your product variations prices. The total number of results could be limited by specifying query parameters. Generally the resulting product variations will be paginated. The default page length is 100 product variations per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V5__getProductVariationPrices",
        "summary": "Read product variations prices",
        "tags": [
          "Products V5"
        ]
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Update your product variation prices and get a process-id to query results. The limit for the number of product variation prices in one request is 500.",
        "operationId": "Products-V5__updateProductVariationPrices",
        "summary": "Update product variation prices",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/update-tasks/{processUuid}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "The response will contain the links for the different parts of the result: products successfully created or updated, products with failures, products which did not contain any changes compared to the last sent version.",
        "operationId": "Products-V5__progressByProcessId",
        "summary": "Request the results of a product data delivery",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/update-tasks/{processUuid}/failed": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Request the failed products of the product data delivery with the linked processUuid. The response will contain a list of failed products with associated error details.",
        "operationId": "Products-V5__failedByProcessId",
        "summary": "List failed products of a product data delivery",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/update-tasks/{processUuid}/succeeded": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Request the succeeded products of the product data delivery with the linked processUuid. The response will contain a list of successfully delivered products.",
        "operationId": "Products-V5__succeededByProcessId",
        "summary": "List succeeded products of a product data delivery",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/update-tasks/{processUuid}/unchanged": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Request the unchanged products of the product data delivery with the linked processUuid. The response will contain a list of unchanged products.",
        "operationId": "Products-V5__unchangedByProcessId",
        "summary": "List unchanged products of a product data delivery",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/{sku}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns a single product variation by SKU.",
        "operationId": "Products-V5__getProductVariation",
        "summary": "Read a single product variation",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/{sku}/active-status": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns active status of the requested product variation by SKU.",
        "operationId": "Products-V5__getVariationActiveStatus",
        "summary": "Read the active status of a single product variation",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/{sku}/content-changes": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns the content changes info for a single product variation within a specific time period. The resulting content changes will be paginated. The default page length is 100 entries per response, also the page size limit. The links specified in the result can be used to page through the total result space.",
        "operationId": "Products-V5__getContentChanges",
        "summary": "Read content changes for a single product variation",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/{sku}/marketplace-status": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Returns marketplace status for a single product variation by SKU.",
        "operationId": "Products-V5__getMarketPlaceStatus",
        "summary": "Read marketplace status for a single product variation",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v5/products/{sku}/prices": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "products"
            ]
          }
        ],
        "description": "Read the price data of a single product variation.",
        "operationId": "Products-V5__getProductVariationPrice",
        "summary": "Read a single product variation price",
        "tags": [
          "Products V5"
        ]
      }
    },
    "/v4/orders": {
      "get": {
        "description": "Retrieve orders sorted by order date from oldest to newest. The number of returned orders is limited to 128; cursor based pagination is supported.",
        "operationId": "Orders-V4__findPartnerOrders",
        "security": [
          {
            "bearerAuth": [
              "orders"
            ]
          }
        ],
        "summary": "List of orders filtered by fulfillment state",
        "tags": [
          "Orders V4"
        ]
      }
    },
    "/v4/orders/{orderNumber}": {
      "get": {
        "description": "Fetch a single order by its unique order number.",
        "operationId": "Orders-V4__getPartnerOrderByOrderNumber",
        "security": [
          {
            "bearerAuth": [
              "orders"
            ]
          }
        ],
        "summary": "Get an order via order number",
        "tags": [
          "Orders V4"
        ]
      }
    },
    "/v4/orders/{salesOrderId}": {
      "get": {
        "description": "Fetch a single order by its unique sales order id.",
        "operationId": "Orders-V4__getPartnerOrderBySalesOrderId",
        "security": [
          {
            "bearerAuth": [
              "orders"
            ]
          }
        ],
        "summary": "Get an order via sales order id",
        "tags": [
          "Orders V4"
        ]
      }
    },
    "/v4/orders/{salesOrderId}/cancellation": {
      "post": {
        "description": "Allows to cancel all position items of one or more orders by salesOrderId.<br>Note: Only position items in state PROCESSABLE can be cancelled. Position items in different states will be ignored. If no position item can be cancelled the operation will respond with a conflict error message.",
        "operationId": "Orders-V4__cancelPartnerOrders",
        "security": [
          {
            "bearerAuth": [
              "orders"
            ]
          }
        ],
        "summary": "Cancel all position items of an order",
        "tags": [
          "Orders V4"
        ]
      }
    },
    "/v4/orders/{salesOrderId}/positionItems/{positionItemIds}/cancellation": {
      "post": {
        "description": "Allows to cancel specific position items of an order by salesOrderId and positionItemIds.<br>Note: Only position items in state PROCESSABLE can be cancelled. Position items in state CANCELLED_BY_PARTNER will be ignored. If any position item is in a different state the operation will leave the whole order unchanged and respond with a conflict error message.",
        "operationId": "Orders-V4__cancelPartnerOrderPositionItems",
        "security": [
          {
            "bearerAuth": [
              "orders"
            ]
          }
        ],
        "summary": "Cancel specific position items of an order",
        "tags": [
          "Orders V4"
        ]
      }
    },
    "/v1/return-shipments": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "ReturnShipments V1"
        ],
        "summary": "Retrieve returnShipments.",
        "description": "This endpoint can be used to retrieve the returned shipments for a given authorized partner.",
        "operationId": "ReturnShipments-V1__listReturnShipmentsUsingGET",
        "deprecated": false
      }
    },
    "/v1/return-shipments/carriers/{carrier}/trackingnumbers/{trackingNumber}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "ReturnShipments V1"
        ],
        "summary": "Retrieve returnShipment by carrier and tracking number.",
        "description": "This endpoint can be used to retrieve a returned shipment by carrier and tracking number.",
        "operationId": "ReturnShipments-V1__returnShipmentByCarrierAndTrackingNumberUsingGET",
        "deprecated": false
      }
    },
    "/v1/return-shipments/{returnShipmentId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "ReturnShipments V1"
        ],
        "summary": "Retrieve returnShipments by returnShipment ID.",
        "description": "This endpoint can be used to retrieve a returned shipment by OTTO internal returnShipment ID.",
        "operationId": "ReturnShipments-V1__returnShipmentUsingGET",
        "deprecated": false
      }
    },
    "/v1/shipments": {
      "post": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "Shipments V1"
        ],
        "summary": "Create a shipment and mark the position items as sent.",
        "description": "This endpoint should be used to create a shipment with a list of position items.",
        "operationId": "Shipments-V1__createdAndSentShipmentUsingPOST",
        "deprecated": false
      },
      "get": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "Shipments V1"
        ],
        "summary": "Retrieve shipments.",
        "description": "This endpoint can be used to retrieve the shipments for a given authorized partner.",
        "operationId": "Shipments-V1__listShipmentsUsingGET",
        "deprecated": false
      }
    },
    "/v1/shipments/carriers/{carrier}/trackingnumbers/{trackingNumber}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "Shipments V1"
        ],
        "summary": "Retrieve shipment by carrier and tracking number.",
        "description": "This endpoint can be used to retrieve a shipment by carrier and tracking number.",
        "operationId": "Shipments-V1__shipmentByCarrierAndTrackingNumberUsingGET",
        "deprecated": false
      }
    },
    "/v1/shipments/{shipmentId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "Shipments V1"
        ],
        "summary": "Retrieve shipment by shipment ID.",
        "description": "This endpoint can be used to retrieve a shipment by OTTO internal shipment ID.",
        "operationId": "Shipments-V1__shipmentUsingGET",
        "deprecated": false
      }
    },
    "/v1/shipments/carriers/{carrier}/trackingnumbers/{trackingNumber}/positionitems": {
      "post": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "Shipments V1"
        ],
        "summary": "Correct an existing shipment (add sent items) by carrier and tracking number.",
        "description": "This endpoint allows to update an existing shipment with new position items.",
        "operationId": "Shipments-V1__appendPositionItemsByCarrierAndTrackingNumberUsingPOST",
        "deprecated": false
      }
    },
    "/v1/shipments/{shipmentId}/positionitems": {
      "post": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "Shipments V1"
        ],
        "summary": "Correct an existing shipment (add sent items) by shipment ID.",
        "description": "This endpoint allows to update an existing shipment with new position items. Note that this is just a correction process for shipments where position items are missing. A separate purchase receipt will be generated for the newly added position items.",
        "operationId": "Shipments-V1__appendPositionItemsUsingPOST",
        "deprecated": false
      }
    },
    "/v1/multiparcel-shipments": {
      "post": {
        "security": [
          {
            "bearerAuth": [
              "shipments"
            ]
          }
        ],
        "tags": [
          "Shipments V1"
        ],
        "summary": "Create a multiparcel shipment and mark the position items as sent.",
        "description": "This endpoint is designed for creating multiparcel shipments when a single article (position item) is sent in multiple shipments, each with its own tracking key.",
        "operationId": "Shipments-V1__createdAndSentMultiparcelShipmentUsingPOST",
        "deprecated": false
      }
    },
    "/v3/returns": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "returns"
            ]
          }
        ],
        "tags": [
          "Returns V3"
        ],
        "summary": "Get all the items filtered on return status",
        "description": "The items will be sorted on status modified time in reverse chronological order. Additionally we provide cursor based pagination via next link. This endpoint is limited to at max 50 results per page",
        "operationId": "Returns-V3__getPositionItemsForUsingGETV3",
        "deprecated": false
      }
    },
    "/v3/returns/acceptance": {
      "post": {
        "security": [
          {
            "bearerAuth": [
              "returns"
            ]
          }
        ],
        "tags": [
          "Returns V3"
        ],
        "summary": "Accept the return for a sent position item (up to 200 items per request)",
        "operationId": "Returns-V3__receiveAcceptedReturnsV3UsingPOSTV3",
        "deprecated": false
      }
    },
    "/v3/returns/rejection": {
      "post": {
        "security": [
          {
            "bearerAuth": [
              "returns"
            ]
          }
        ],
        "tags": [
          "Returns V3"
        ],
        "summary": "Reject the return for a sent position item (up to 200 items per request)",
        "operationId": "Returns-V3__receiveRejectedReturnsV3UsingPOSTV3",
        "deprecated": false
      }
    },
    "/v3/receipts/{receiptNumber}.pdf": {
      "get": {
        "tags": [
          "Receipts V3"
        ],
        "summary": "Get the PDF document of a specific receipt",
        "description": "Get PDF document by 'receiptNumber'",
        "operationId": "Receipts-V3__getReceiptPdfUsingGET_3",
        "security": [
          {
            "bearerAuth": [
              "receipts"
            ]
          }
        ]
      }
    },
    "/v3/receipts/{receiptNumber}": {
      "get": {
        "tags": [
          "Receipts V3"
        ],
        "summary": "Get the JSON object of a specific receipt",
        "description": "Get JSON object by the 'receiptNumber'",
        "operationId": "Receipts-V3__getReceiptUsingGET_5",
        "security": [
          {
            "bearerAuth": [
              "receipts"
            ]
          }
        ]
      }
    },
    "/v3/receipts": {
      "get": {
        "tags": [
          "Receipts V3"
        ],
        "summary": "Get receipts as list of JSON objects",
        "description": "Retrieve receips sorted by creation date, latest ones first. The number of receipts is limited to 128 results; cursor based pagination is supported.",
        "operationId": "Receipts-V3__getReceiptsUsingGET_5",
        "security": [
          {
            "bearerAuth": [
              "receipts"
            ]
          }
        ]
      }
    },
    "/v1/price-reductions": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "price-reduction"
            ]
          }
        ],
        "tags": [
          "Price Reductions V1"
        ],
        "summary": "Get all priceReductions",
        "description": "This API can be used to fetch the price reduction for a single positionItemId by providing positionId as a query parameter in the request. If the positionItemId is not specified, then this api would list the price reductions for all your products.",
        "operationId": "Price-Reductions-V1__getAllReductionsForPartner"
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "price-reduction"
            ]
          }
        ],
        "tags": [
          "Price Reductions V1"
        ],
        "summary": "Apply price reduction for a positionItemId",
        "description": "Apply price reduction on a positionItemId",
        "operationId": "Price-Reductions-V1__applyPriceReduction"
      }
    },
    "/v2/returns-warehouse/addresses": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-read"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "get all returnWarehouse addresses",
        "description": "This GET API endpoint is to fetch all return warehouse addresses.\nResponse is by default paginated with default page size of 50.\n",
        "operationId": "ReturnsWarehouse-V2__getAllReturnsWarehouseAddresses",
        "deprecated": false
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-write"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "create returnWarehouse address",
        "description": "This POST API endpoint is to add a new return warehouse address.\n\nA new return address will always be created after verifying it is not a duplicate.\n\nThe address will be validated before being saved.\n\nWhen the warehouse type is `INTERNATIONAL_CONSOLIDATION_HUB`, address details should not be entered. \nThe address is automatically set to `Robert-Bosch-Breite 10, 37079 Göttingen, Germany`.\n`INTERNATIONAL_CONSOLIDATION_HUB` cannot be a misdirected/standard address, y[...]",
        "operationId": "ReturnsWarehouse-V2__createReturnWarehouseAddress",
        "deprecated": false
      }
    },
    "/v2/returns-warehouse/addresses/{returnAddressId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-read"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "get returnWarehouse address by returnAddressId",
        "description": "This GET API endpoint retrieves the return warehouse address for a partner based on the provided ID.\n",
        "operationId": "ReturnsWarehouse-V2__getReturnsWarehouseAddressById",
        "deprecated": false
      },
      "put": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-write"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "update returnWarehouse address by returnAddressId",
        "description": "This PUT API endpoint is to update a return warehouse address.\n\nAddress will be validated before being saved.\n\nWhen the warehouse type is `INTERNATIONAL_CONSOLIDATION_HUB`, address details should not be entered. \nThe address is automatically set to `Robert-Bosch-Breite 10, 37079 Göttingen, Germany`.\n\nThe country and warehouse type of the return warehouse address cannot be updated. Zipcode changes are restricted for addresses linked to a DHL carrier.\n",
        "operationId": "ReturnsWarehouse-V2__updateReturnWarehouseAddress",
        "deprecated": false
      },
      "delete": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-write"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "delete returnWarehouse address by returnAddressId",
        "description": "This DELETE API endpoint is to delete a return warehouse address by id.\n\n**Deleting a misdirected address is not allowed.**\n**Deleting an address which has one or more return carrier(s) is not allowed.**\n",
        "operationId": "ReturnsWarehouse-V2__deleteReturnsWarehouseAddressById",
        "deprecated": false
      }
    },
    "/v2/returns-warehouse/addresses/{returnAddressId}/carriers": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-read"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "get returnWarehouse Carriers by returnAddressId",
        "description": "This GET API endpoint retrieves the return warehouse carriers associated with a partner for a specific address, identified by the Return Address ID.\n",
        "operationId": "ReturnsWarehouse-V2__getReturnsWarehouseCarriersByReturnAddressId",
        "deprecated": false
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-write"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "create returnCarrier for returnWarehouse address",
        "description": "This POST API endpoint is used to add a return carrier and its associated routing codes to a specified return warehouse.\n\nTo add a carrier, the return warehouse must be identified by its ID. \n\nEnsure that a return warehouse address has been created before adding a parcel return carrier. \nThe warehouse address can be created using the `create a parcel return address` (POST ).\n\nThe Return Address ID must be provided as a path parameter.\n",
        "operationId": "ReturnsWarehouse-V2__createReturnsWarehouseCarrier",
        "deprecated": false
      }
    },
    "/v2/returns-warehouse/addresses/{returnAddressId}/carriers/{returnAddressCarrierId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-read"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "get returnWarehouse Carriers by returnAddressCarrierId",
        "description": "This GET API endpoint retrieves a specific return warehouse carrier of a partner using the Return Address ID and Carrier ID.\n",
        "operationId": "ReturnsWarehouse-V2__getReturnsWarehouseCarriersByReturnAddressIdAndReturnAddressCarrierId",
        "deprecated": false
      },
      "put": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-write"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "update returnCarrier for returnWarehouse address",
        "description": "This PUT API endpoint is used to update an existing parcel return carrier by its ID.\n\nThe PUT request will only allow updating the carrier codes.\n\n**Note that the HERMES carrier does not have carrier codes, so it cannot be updated.**\n",
        "operationId": "ReturnsWarehouse-V2__updateParcelReturnCarrier",
        "deprecated": false
      },
      "delete": {
        "security": [
          {
            "bearerAuth": [
              "returns-warehouse-write"
            ]
          }
        ],
        "tags": [
          "ReturnsWarehouse V2"
        ],
        "summary": "delete returnCarrier for returnWarehouse address",
        "description": "This DELETE API endpoint is to delete a return address carrier by id.\n",
        "operationId": "ReturnsWarehouse-V2__deleteParcelReturnCarrier",
        "deprecated": false
      }
    },
    "/v1/shipping-profiles": {
      "post": {
        "security": [
          {
            "bearerAuth": [
              "shipping-profiles"
            ]
          }
        ],
        "tags": [
          "ShippingProfiles V1"
        ],
        "summary": "Create shipping profile",
        "description": "This POST API endpoint is to create shipping profile API\nPOST will always create a new shipping profile after ensuring it is not a duplicate for a partner.\n",
        "operationId": "ShippingProfiles-V1__createShippingProfile",
        "deprecated": false
      },
      "get": {
        "security": [
          {
            "bearerAuth": [
              "shipping-profiles"
            ]
          }
        ],
        "tags": [
          "ShippingProfiles V1"
        ],
        "summary": "Get all shipping profiles from a partner",
        "description": "This GET API endpoint is to get all shipping profiles for a partner.\nResponse is by default paginated with default page size of 300.\n",
        "operationId": "ShippingProfiles-V1__getShippingProfiles",
        "deprecated": false
      }
    },
    "/v1/shipping-profiles/{shippingProfileId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "shipping-profiles"
            ]
          }
        ],
        "tags": [
          "ShippingProfiles V1"
        ],
        "summary": "Get shipping profile by shipping profile id",
        "description": "This GET API endpoint is to get a shipping profile of the partner by shipping profile id.\n",
        "operationId": "ShippingProfiles-V1__getShippingProfileById",
        "deprecated": false
      },
      "put": {
        "security": [
          {
            "bearerAuth": [
              "shipping-profiles"
            ]
          }
        ],
        "tags": [
          "ShippingProfiles V1"
        ],
        "summary": "Update shipping profile",
        "description": "This PUT API endpoint is to update a shipping profile\nPUT will always take an shipping profile and update it. \ndeliveryType field cannot be updated\n",
        "operationId": "ShippingProfiles-V1__updateShippingProfile",
        "deprecated": false
      },
      "delete": {
        "security": [
          {
            "bearerAuth": [
              "shipping-profiles"
            ]
          }
        ],
        "tags": [
          "ShippingProfiles V1"
        ],
        "summary": "Delete shipping profile",
        "description": "This DELETE API endpoint is to delete a shipping profile by id.\n",
        "operationId": "ShippingProfiles-V1__deleteShippingProfile",
        "deprecated": false
      }
    },
    "/v1/availability/quantities": {
      "post": {
        "security": [
          {
            "bearerAuth": [
              "availability"
            ]
          }
        ],
        "tags": [
          "Availability V1"
        ],
        "summary": "Update quantities",
        "operationId": "Availability-V1__storeAvailableQuantitiesUsingPOST",
        "deprecated": false
      },
      "get": {
        "security": [
          {
            "bearerAuth": [
              "availability"
            ]
          }
        ],
        "tags": [
          "Availability V1"
        ],
        "summary": "Get quantities from a partner (up to 200 per request)",
        "description": "Retrieve available quantities sorted by sku name in ascending.The maximum number of returned quantities is limited to 200.",
        "operationId": "Availability-V1__getAvailableQuantities",
        "deprecated": false
      }
    },
    "/v1/availability/quantities/{sku}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "availability"
            ]
          }
        ],
        "tags": [
          "Availability V1"
        ],
        "summary": "Get quantity for a sku",
        "description": "Fetch a single available quantity by its unique sku name.",
        "operationId": "Availability-V1__getAvailableQuantityBySku",
        "deprecated": false
      }
    },
    "/v1/availability/product-delivery-information": {
      "post": {
        "security": [
          {
            "bearerAuth": [
              "availability"
            ]
          }
        ],
        "tags": [
          "Availability V1"
        ],
        "summary": "Update product delivery information",
        "operationId": "Availability-V1__storeProductDeliveryInformationUsingPOST",
        "deprecated": false
      },
      "get": {
        "security": [
          {
            "bearerAuth": [
              "availability"
            ]
          }
        ],
        "tags": [
          "Availability V1"
        ],
        "summary": "Get product delivery information from a partner",
        "description": "Retrieve sku and shipping profile mapping.The maximum number of returned items is limited to 200. If there are more items, a cursor field is returned to get the next results.",
        "operationId": "Availability-V1__getProductDeliveryInformation",
        "deprecated": false
      }
    },
    "/v1/availability/product-delivery-information/{sku}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "availability"
            ]
          }
        ],
        "tags": [
          "Availability V1"
        ],
        "summary": "Get product delivery information for a SKU",
        "description": "This GET API endpoint is to get a shipping profile id and processing time for given sku\n",
        "operationId": "Availability-V1__getDeliveryInformationBySKU",
        "deprecated": false
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "tags": [
    {
      "name": "Products V4",
      "description": ""
    },
    {
      "name": "Products V5",
      "description": ""
    },
    {
      "name": "Orders V4",
      "description": ""
    },
    {
      "name": "ReturnShipments V1",
      "description": ""
    },
    {
      "name": "Shipments V1",
      "description": ""
    },
    {
      "name": "Returns V3",
      "description": ""
    },
    {
      "name": "Receipts V3",
      "description": ""
    },
    {
      "name": "Price Reductions V1",
      "description": ""
    },
    {
      "name": "ReturnsWarehouse V2",
      "description": ""
    },
    {
      "name": "ShippingProfiles V1",
      "description": ""
    },
    {
      "name": "Availability V1",
      "description": ""
    }
  ]
}