<?php
/**
 * ALLApi
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orders
 *
 * This API documentation describes all endpoints for orders - version 3
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Otto\Client\Orders\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Otto\Client\ApiException;
use Otto\Client\Configuration;
use Otto\Client\HeaderSelector;
use Otto\Client\ObjectSerializer;

/**
 * ALLApi Class Doc Comment
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ALLApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation cancelPartnerOrderPositionItems
     *
     * Cancels PositionItems of an order by ids
     *
     * @param  string $sales_order_id The Sales Order Id of the order to cancel (required)
     * @param  string[] $position_item_id The ids of the PositionItems to cancel (required)
     *
     * @throws \Otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function cancelPartnerOrderPositionItems($sales_order_id, $position_item_id)
    {
        $this->cancelPartnerOrderPositionItemsWithHttpInfo($sales_order_id, $position_item_id);
    }

    /**
     * Operation cancelPartnerOrderPositionItemsWithHttpInfo
     *
     * Cancels PositionItems of an order by ids
     *
     * @param  string $sales_order_id The Sales Order Id of the order to cancel (required)
     * @param  string[] $position_item_id The ids of the PositionItems to cancel (required)
     *
     * @throws \Otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelPartnerOrderPositionItemsWithHttpInfo($sales_order_id, $position_item_id)
    {
        $returnType = '';
        $request = $this->cancelPartnerOrderPositionItemsRequest($sales_order_id, $position_item_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation cancelPartnerOrderPositionItemsAsync
     *
     * Cancels PositionItems of an order by ids
     *
     * @param  string $sales_order_id The Sales Order Id of the order to cancel (required)
     * @param  string[] $position_item_id The ids of the PositionItems to cancel (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelPartnerOrderPositionItemsAsync($sales_order_id, $position_item_id)
    {
        return $this->cancelPartnerOrderPositionItemsAsyncWithHttpInfo($sales_order_id, $position_item_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cancelPartnerOrderPositionItemsAsyncWithHttpInfo
     *
     * Cancels PositionItems of an order by ids
     *
     * @param  string $sales_order_id The Sales Order Id of the order to cancel (required)
     * @param  string[] $position_item_id The ids of the PositionItems to cancel (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelPartnerOrderPositionItemsAsyncWithHttpInfo($sales_order_id, $position_item_id)
    {
        $returnType = '';
        $request = $this->cancelPartnerOrderPositionItemsRequest($sales_order_id, $position_item_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'cancelPartnerOrderPositionItems'
     *
     * @param  string $sales_order_id The Sales Order Id of the order to cancel (required)
     * @param  string[] $position_item_id The ids of the PositionItems to cancel (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function cancelPartnerOrderPositionItemsRequest($sales_order_id, $position_item_id)
    {
        // verify the required parameter 'sales_order_id' is set
        if ($sales_order_id === null || (is_array($sales_order_id) && count($sales_order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sales_order_id when calling cancelPartnerOrderPositionItems'
            );
        }
        // verify the required parameter 'position_item_id' is set
        if ($position_item_id === null || (is_array($position_item_id) && count($position_item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $position_item_id when calling cancelPartnerOrderPositionItems'
            );
        }

        $resourcePath = '/v3/orders/{salesOrderId}/positionItems/{positionItemId}/cancellation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($sales_order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'salesOrderId' . '}',
                ObjectSerializer::toPathValue($sales_order_id),
                $resourcePath
            );
        }
        // path params
        if ($position_item_id !== null) {
            $resourcePath = str_replace(
                '{' . 'positionItemId' . '}',
                ObjectSerializer::toPathValue($position_item_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation cancelPartnerOrders
     *
     * Cancel all PositionItems of an order
     *
     * @param  string[] $sales_order_id The Sales Order Id of the order to cancel (required)
     *
     * @throws \Otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function cancelPartnerOrders($sales_order_id)
    {
        $this->cancelPartnerOrdersWithHttpInfo($sales_order_id);
    }

    /**
     * Operation cancelPartnerOrdersWithHttpInfo
     *
     * Cancel all PositionItems of an order
     *
     * @param  string[] $sales_order_id The Sales Order Id of the order to cancel (required)
     *
     * @throws \Otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelPartnerOrdersWithHttpInfo($sales_order_id)
    {
        $returnType = '';
        $request = $this->cancelPartnerOrdersRequest($sales_order_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation cancelPartnerOrdersAsync
     *
     * Cancel all PositionItems of an order
     *
     * @param  string[] $sales_order_id The Sales Order Id of the order to cancel (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelPartnerOrdersAsync($sales_order_id)
    {
        return $this->cancelPartnerOrdersAsyncWithHttpInfo($sales_order_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cancelPartnerOrdersAsyncWithHttpInfo
     *
     * Cancel all PositionItems of an order
     *
     * @param  string[] $sales_order_id The Sales Order Id of the order to cancel (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelPartnerOrdersAsyncWithHttpInfo($sales_order_id)
    {
        $returnType = '';
        $request = $this->cancelPartnerOrdersRequest($sales_order_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'cancelPartnerOrders'
     *
     * @param  string[] $sales_order_id The Sales Order Id of the order to cancel (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function cancelPartnerOrdersRequest($sales_order_id)
    {
        // verify the required parameter 'sales_order_id' is set
        if ($sales_order_id === null || (is_array($sales_order_id) && count($sales_order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sales_order_id when calling cancelPartnerOrders'
            );
        }

        $resourcePath = '/v3/orders/{salesOrderId}/cancellation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($sales_order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'salesOrderId' . '}',
                ObjectSerializer::toPathValue($sales_order_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findPartnerOrders
     *
     * Get a list of orders which can be filtered on fulfillmentStatus.
     *
     * @param  string $from_date Defines, which minimum lifecycle change date the returned order should have. In ISO 8601 format. (optional)
     * @param  string $fulfillment_status Defines, which minimum state the returned orders should have.&lt;br&gt;If ANNOUNCED is given, all orders, which have at least one PositionItem in ANNOUNCED state are returned.&lt;br&gt;If PROCESSABLE is given, all orders, which have at least one PositionItem in PROCESSABLE state and none in ANNOUNCED state are returned.&lt;br&gt;If SENT is given, all orders, which have at least one PositionItem in SENT state and none in either ANNOUNCED or PROCESSABLE state are returned.&lt;br&gt;If RETURNED is given, all orders, which have at least one PositionItem in RETURNED state and none in either ANNOUNCED or PROCESSABLE or SENT state are returned.&lt;br&gt;If CANCELLED_BY_PARTNER is given, all orders, which have at least one PositionItem in CANCELLED_BY_PARTNER state are returned.&lt;br&gt;If CANCELLED_BY_MARKETPLACE is given, all orders, which have at least one PositionItem in CANCELLED_BY_MARKETPLACE state are returned.&lt;br&gt;If none is provided, all status will be returned.&lt;br&gt;Several values can be passed via request param array, when multiple values passed, search result will be combination of multiple fulfillmentStatuses - no duplicates will appear.&lt;br&gt;Example: ?fulfillmentStatus&#x3D;PROCESSABLE&amp;fulfillmentStatus&#x3D;CANCELLED_BY_MARKETPLACE - will return orders in these 3 fulfillmentStatuses.&lt;br&gt;Alternatively, mode can be passed for a different search type. BUCKET/AT_LEAST_ONE, where BUCKET is default behaviour explained above and AT_LEAST_ONE checks if there is at least 1 PositionItem with passed fulfillmentStatus/fulfillmentStatuses. (optional)
     * @param  int $limit The maximum amount of returned orders (optional, default to 128)
     * @param  string $order_direction order_direction (optional, default to ASC)
     * @param  string $order_column_type order_column_type (optional, default to ORDER_LIFECYCLE_DATE)
     * @param  string $mode The search mode. Default search mode is bucket search (optional, default to BUCKET)
     * @param  string $nextcursor For paging request this cursor is required. If a next cursor is provided, the only other request parameter being considered is &#x27;limit&#x27;. (optional)
     * @param  string $search_term The search term for partial text search. (optional)
     *
     * @throws \Otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Otto\Client\Orders\Model\PartnerOrderList
     */
    public function findPartnerOrders($from_date = null, $fulfillment_status = null, $limit = '128', $order_direction = 'ASC', $order_column_type = 'ORDER_LIFECYCLE_DATE', $mode = 'BUCKET', $nextcursor = null, $search_term = null)
    {
        list($response) = $this->findPartnerOrdersWithHttpInfo($from_date, $fulfillment_status, $limit, $order_direction, $order_column_type, $mode, $nextcursor, $search_term);
        return $response;
    }

    /**
     * Operation findPartnerOrdersWithHttpInfo
     *
     * Get a list of orders which can be filtered on fulfillmentStatus.
     *
     * @param  string $from_date Defines, which minimum lifecycle change date the returned order should have. In ISO 8601 format. (optional)
     * @param  string $fulfillment_status Defines, which minimum state the returned orders should have.&lt;br&gt;If ANNOUNCED is given, all orders, which have at least one PositionItem in ANNOUNCED state are returned.&lt;br&gt;If PROCESSABLE is given, all orders, which have at least one PositionItem in PROCESSABLE state and none in ANNOUNCED state are returned.&lt;br&gt;If SENT is given, all orders, which have at least one PositionItem in SENT state and none in either ANNOUNCED or PROCESSABLE state are returned.&lt;br&gt;If RETURNED is given, all orders, which have at least one PositionItem in RETURNED state and none in either ANNOUNCED or PROCESSABLE or SENT state are returned.&lt;br&gt;If CANCELLED_BY_PARTNER is given, all orders, which have at least one PositionItem in CANCELLED_BY_PARTNER state are returned.&lt;br&gt;If CANCELLED_BY_MARKETPLACE is given, all orders, which have at least one PositionItem in CANCELLED_BY_MARKETPLACE state are returned.&lt;br&gt;If none is provided, all status will be returned.&lt;br&gt;Several values can be passed via request param array, when multiple values passed, search result will be combination of multiple fulfillmentStatuses - no duplicates will appear.&lt;br&gt;Example: ?fulfillmentStatus&#x3D;PROCESSABLE&amp;fulfillmentStatus&#x3D;CANCELLED_BY_MARKETPLACE - will return orders in these 3 fulfillmentStatuses.&lt;br&gt;Alternatively, mode can be passed for a different search type. BUCKET/AT_LEAST_ONE, where BUCKET is default behaviour explained above and AT_LEAST_ONE checks if there is at least 1 PositionItem with passed fulfillmentStatus/fulfillmentStatuses. (optional)
     * @param  int $limit The maximum amount of returned orders (optional, default to 128)
     * @param  string $order_direction (optional, default to ASC)
     * @param  string $order_column_type (optional, default to ORDER_LIFECYCLE_DATE)
     * @param  string $mode The search mode. Default search mode is bucket search (optional, default to BUCKET)
     * @param  string $nextcursor For paging request this cursor is required. If a next cursor is provided, the only other request parameter being considered is &#x27;limit&#x27;. (optional)
     * @param  string $search_term The search term for partial text search. (optional)
     *
     * @throws \Otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Otto\Client\Orders\Model\PartnerOrderList, HTTP status code, HTTP response headers (array of strings)
     */
    public function findPartnerOrdersWithHttpInfo($from_date = null, $fulfillment_status = null, $limit = '128', $order_direction = 'ASC', $order_column_type = 'ORDER_LIFECYCLE_DATE', $mode = 'BUCKET', $nextcursor = null, $search_term = null)
    {
        $returnType = '\Otto\Client\Orders\Model\PartnerOrderList';
        $request = $this->findPartnerOrdersRequest($from_date, $fulfillment_status, $limit, $order_direction, $order_column_type, $mode, $nextcursor, $search_term);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Otto\Client\Orders\Model\PartnerOrderList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findPartnerOrdersAsync
     *
     * Get a list of orders which can be filtered on fulfillmentStatus.
     *
     * @param  string $from_date Defines, which minimum lifecycle change date the returned order should have. In ISO 8601 format. (optional)
     * @param  string $fulfillment_status Defines, which minimum state the returned orders should have.&lt;br&gt;If ANNOUNCED is given, all orders, which have at least one PositionItem in ANNOUNCED state are returned.&lt;br&gt;If PROCESSABLE is given, all orders, which have at least one PositionItem in PROCESSABLE state and none in ANNOUNCED state are returned.&lt;br&gt;If SENT is given, all orders, which have at least one PositionItem in SENT state and none in either ANNOUNCED or PROCESSABLE state are returned.&lt;br&gt;If RETURNED is given, all orders, which have at least one PositionItem in RETURNED state and none in either ANNOUNCED or PROCESSABLE or SENT state are returned.&lt;br&gt;If CANCELLED_BY_PARTNER is given, all orders, which have at least one PositionItem in CANCELLED_BY_PARTNER state are returned.&lt;br&gt;If CANCELLED_BY_MARKETPLACE is given, all orders, which have at least one PositionItem in CANCELLED_BY_MARKETPLACE state are returned.&lt;br&gt;If none is provided, all status will be returned.&lt;br&gt;Several values can be passed via request param array, when multiple values passed, search result will be combination of multiple fulfillmentStatuses - no duplicates will appear.&lt;br&gt;Example: ?fulfillmentStatus&#x3D;PROCESSABLE&amp;fulfillmentStatus&#x3D;CANCELLED_BY_MARKETPLACE - will return orders in these 3 fulfillmentStatuses.&lt;br&gt;Alternatively, mode can be passed for a different search type. BUCKET/AT_LEAST_ONE, where BUCKET is default behaviour explained above and AT_LEAST_ONE checks if there is at least 1 PositionItem with passed fulfillmentStatus/fulfillmentStatuses. (optional)
     * @param  int $limit The maximum amount of returned orders (optional, default to 128)
     * @param  string $order_direction (optional, default to ASC)
     * @param  string $order_column_type (optional, default to ORDER_LIFECYCLE_DATE)
     * @param  string $mode The search mode. Default search mode is bucket search (optional, default to BUCKET)
     * @param  string $nextcursor For paging request this cursor is required. If a next cursor is provided, the only other request parameter being considered is &#x27;limit&#x27;. (optional)
     * @param  string $search_term The search term for partial text search. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findPartnerOrdersAsync($from_date = null, $fulfillment_status = null, $limit = '128', $order_direction = 'ASC', $order_column_type = 'ORDER_LIFECYCLE_DATE', $mode = 'BUCKET', $nextcursor = null, $search_term = null)
    {
        return $this->findPartnerOrdersAsyncWithHttpInfo($from_date, $fulfillment_status, $limit, $order_direction, $order_column_type, $mode, $nextcursor, $search_term)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findPartnerOrdersAsyncWithHttpInfo
     *
     * Get a list of orders which can be filtered on fulfillmentStatus.
     *
     * @param  string $from_date Defines, which minimum lifecycle change date the returned order should have. In ISO 8601 format. (optional)
     * @param  string $fulfillment_status Defines, which minimum state the returned orders should have.&lt;br&gt;If ANNOUNCED is given, all orders, which have at least one PositionItem in ANNOUNCED state are returned.&lt;br&gt;If PROCESSABLE is given, all orders, which have at least one PositionItem in PROCESSABLE state and none in ANNOUNCED state are returned.&lt;br&gt;If SENT is given, all orders, which have at least one PositionItem in SENT state and none in either ANNOUNCED or PROCESSABLE state are returned.&lt;br&gt;If RETURNED is given, all orders, which have at least one PositionItem in RETURNED state and none in either ANNOUNCED or PROCESSABLE or SENT state are returned.&lt;br&gt;If CANCELLED_BY_PARTNER is given, all orders, which have at least one PositionItem in CANCELLED_BY_PARTNER state are returned.&lt;br&gt;If CANCELLED_BY_MARKETPLACE is given, all orders, which have at least one PositionItem in CANCELLED_BY_MARKETPLACE state are returned.&lt;br&gt;If none is provided, all status will be returned.&lt;br&gt;Several values can be passed via request param array, when multiple values passed, search result will be combination of multiple fulfillmentStatuses - no duplicates will appear.&lt;br&gt;Example: ?fulfillmentStatus&#x3D;PROCESSABLE&amp;fulfillmentStatus&#x3D;CANCELLED_BY_MARKETPLACE - will return orders in these 3 fulfillmentStatuses.&lt;br&gt;Alternatively, mode can be passed for a different search type. BUCKET/AT_LEAST_ONE, where BUCKET is default behaviour explained above and AT_LEAST_ONE checks if there is at least 1 PositionItem with passed fulfillmentStatus/fulfillmentStatuses. (optional)
     * @param  int $limit The maximum amount of returned orders (optional, default to 128)
     * @param  string $order_direction (optional, default to ASC)
     * @param  string $order_column_type (optional, default to ORDER_LIFECYCLE_DATE)
     * @param  string $mode The search mode. Default search mode is bucket search (optional, default to BUCKET)
     * @param  string $nextcursor For paging request this cursor is required. If a next cursor is provided, the only other request parameter being considered is &#x27;limit&#x27;. (optional)
     * @param  string $search_term The search term for partial text search. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findPartnerOrdersAsyncWithHttpInfo($from_date = null, $fulfillment_status = null, $limit = '128', $order_direction = 'ASC', $order_column_type = 'ORDER_LIFECYCLE_DATE', $mode = 'BUCKET', $nextcursor = null, $search_term = null)
    {
        $returnType = '\Otto\Client\Orders\Model\PartnerOrderList';
        $request = $this->findPartnerOrdersRequest($from_date, $fulfillment_status, $limit, $order_direction, $order_column_type, $mode, $nextcursor, $search_term);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findPartnerOrders'
     *
     * @param  string $from_date Defines, which minimum lifecycle change date the returned order should have. In ISO 8601 format. (optional)
     * @param  string $fulfillment_status Defines, which minimum state the returned orders should have.&lt;br&gt;If ANNOUNCED is given, all orders, which have at least one PositionItem in ANNOUNCED state are returned.&lt;br&gt;If PROCESSABLE is given, all orders, which have at least one PositionItem in PROCESSABLE state and none in ANNOUNCED state are returned.&lt;br&gt;If SENT is given, all orders, which have at least one PositionItem in SENT state and none in either ANNOUNCED or PROCESSABLE state are returned.&lt;br&gt;If RETURNED is given, all orders, which have at least one PositionItem in RETURNED state and none in either ANNOUNCED or PROCESSABLE or SENT state are returned.&lt;br&gt;If CANCELLED_BY_PARTNER is given, all orders, which have at least one PositionItem in CANCELLED_BY_PARTNER state are returned.&lt;br&gt;If CANCELLED_BY_MARKETPLACE is given, all orders, which have at least one PositionItem in CANCELLED_BY_MARKETPLACE state are returned.&lt;br&gt;If none is provided, all status will be returned.&lt;br&gt;Several values can be passed via request param array, when multiple values passed, search result will be combination of multiple fulfillmentStatuses - no duplicates will appear.&lt;br&gt;Example: ?fulfillmentStatus&#x3D;PROCESSABLE&amp;fulfillmentStatus&#x3D;CANCELLED_BY_MARKETPLACE - will return orders in these 3 fulfillmentStatuses.&lt;br&gt;Alternatively, mode can be passed for a different search type. BUCKET/AT_LEAST_ONE, where BUCKET is default behaviour explained above and AT_LEAST_ONE checks if there is at least 1 PositionItem with passed fulfillmentStatus/fulfillmentStatuses. (optional)
     * @param  int $limit The maximum amount of returned orders (optional, default to 128)
     * @param  string $order_direction (optional, default to ASC)
     * @param  string $order_column_type (optional, default to ORDER_LIFECYCLE_DATE)
     * @param  string $mode The search mode. Default search mode is bucket search (optional, default to BUCKET)
     * @param  string $nextcursor For paging request this cursor is required. If a next cursor is provided, the only other request parameter being considered is &#x27;limit&#x27;. (optional)
     * @param  string $search_term The search term for partial text search. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function findPartnerOrdersRequest($from_date = null, $fulfillment_status = null, $limit = '128', $order_direction = 'ASC', $order_column_type = 'ORDER_LIFECYCLE_DATE', $mode = 'BUCKET', $nextcursor = null, $search_term = null)
    {

        $resourcePath = '/v3/orders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from_date !== null) {
            $queryParams['fromDate'] = ObjectSerializer::toQueryValue($from_date);
        }
        // query params
        if ($fulfillment_status !== null) {
            $queryParams['fulfillmentStatus'] = ObjectSerializer::toQueryValue($fulfillment_status);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($order_direction !== null) {
            $queryParams['orderDirection'] = ObjectSerializer::toQueryValue($order_direction);
        }
        // query params
        if ($order_column_type !== null) {
            $queryParams['orderColumnType'] = ObjectSerializer::toQueryValue($order_column_type);
        }
        // query params
        if ($mode !== null) {
            $queryParams['mode'] = ObjectSerializer::toQueryValue($mode);
        }
        // query params
        if ($nextcursor !== null) {
            $queryParams['nextcursor'] = ObjectSerializer::toQueryValue($nextcursor);
        }
        // query params
        if ($search_term !== null) {
            $queryParams['searchTerm'] = ObjectSerializer::toQueryValue($search_term);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPartnerOrderBySalesOrderId
     *
     * Get a single order via Sales Order Id
     *
     * @param  string $sales_order_id The salesOrderId used for searching (required)
     *
     * @throws \Otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Otto\Client\Orders\Model\PartnerOrder
     */
    public function getPartnerOrderBySalesOrderId($sales_order_id)
    {
        list($response) = $this->getPartnerOrderBySalesOrderIdWithHttpInfo($sales_order_id);
        return $response;
    }

    /**
     * Operation getPartnerOrderBySalesOrderIdWithHttpInfo
     *
     * Get a single order via Sales Order Id
     *
     * @param  string $sales_order_id The salesOrderId used for searching (required)
     *
     * @throws \Otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Otto\Client\Orders\Model\PartnerOrder, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPartnerOrderBySalesOrderIdWithHttpInfo($sales_order_id)
    {
        $returnType = '\Otto\Client\Orders\Model\PartnerOrder';
        $request = $this->getPartnerOrderBySalesOrderIdRequest($sales_order_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Otto\Client\Orders\Model\PartnerOrder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPartnerOrderBySalesOrderIdAsync
     *
     * Get a single order via Sales Order Id
     *
     * @param  string $sales_order_id The salesOrderId used for searching (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPartnerOrderBySalesOrderIdAsync($sales_order_id)
    {
        return $this->getPartnerOrderBySalesOrderIdAsyncWithHttpInfo($sales_order_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPartnerOrderBySalesOrderIdAsyncWithHttpInfo
     *
     * Get a single order via Sales Order Id
     *
     * @param  string $sales_order_id The salesOrderId used for searching (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPartnerOrderBySalesOrderIdAsyncWithHttpInfo($sales_order_id)
    {
        $returnType = '\Otto\Client\Orders\Model\PartnerOrder';
        $request = $this->getPartnerOrderBySalesOrderIdRequest($sales_order_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPartnerOrderBySalesOrderId'
     *
     * @param  string $sales_order_id The salesOrderId used for searching (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getPartnerOrderBySalesOrderIdRequest($sales_order_id)
    {
        // verify the required parameter 'sales_order_id' is set
        if ($sales_order_id === null || (is_array($sales_order_id) && count($sales_order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sales_order_id when calling getPartnerOrderBySalesOrderId'
            );
        }

        $resourcePath = '/v3/orders/{salesOrderId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($sales_order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'salesOrderId' . '}',
                ObjectSerializer::toPathValue($sales_order_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
