<?php
/**
 * LinkedItemDetailsReceiptsV3
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Otto\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Otto\Client\Model;

use \ArrayAccess;
use \Otto\Client\ObjectSerializer;

/**
 * LinkedItemDetailsReceiptsV3 Class Doc Comment
 *
 * @category Class
 * @description Additional information to an item directly related to the service. &lt;/br&gt;Object exists only if the service was sold together with an item
 * @package  Otto\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LinkedItemDetailsReceiptsV3 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LinkedItemDetails__Receipts-V3';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'item_receipt_number' => 'string',
        'item_partner_name' => 'string',
        'sku' => 'string',
        'article_number' => 'string',
        'product_title' => 'string',
        'service_relations' => '\Otto\Client\Model\ServiceRelationReceiptsV3[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'item_receipt_number' => null,
        'item_partner_name' => null,
        'sku' => null,
        'article_number' => null,
        'product_title' => null,
        'service_relations' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'item_receipt_number' => false,
        'item_partner_name' => false,
        'sku' => false,
        'article_number' => false,
        'product_title' => false,
        'service_relations' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'item_receipt_number' => 'itemReceiptNumber',
        'item_partner_name' => 'itemPartnerName',
        'sku' => 'sku',
        'article_number' => 'articleNumber',
        'product_title' => 'productTitle',
        'service_relations' => 'serviceRelations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'item_receipt_number' => 'setItemReceiptNumber',
        'item_partner_name' => 'setItemPartnerName',
        'sku' => 'setSku',
        'article_number' => 'setArticleNumber',
        'product_title' => 'setProductTitle',
        'service_relations' => 'setServiceRelations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'item_receipt_number' => 'getItemReceiptNumber',
        'item_partner_name' => 'getItemPartnerName',
        'sku' => 'getSku',
        'article_number' => 'getArticleNumber',
        'product_title' => 'getProductTitle',
        'service_relations' => 'getServiceRelations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('item_receipt_number', $data ?? [], null);
        $this->setIfExists('item_partner_name', $data ?? [], null);
        $this->setIfExists('sku', $data ?? [], null);
        $this->setIfExists('article_number', $data ?? [], null);
        $this->setIfExists('product_title', $data ?? [], null);
        $this->setIfExists('service_relations', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['article_number'] === null) {
            $invalidProperties[] = "'article_number' can't be null";
        }
        if ($this->container['product_title'] === null) {
            $invalidProperties[] = "'product_title' can't be null";
        }
        if ($this->container['service_relations'] === null) {
            $invalidProperties[] = "'service_relations' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets item_receipt_number
     *
     * @return string|null
     */
    public function getItemReceiptNumber()
    {
        return $this->container['item_receipt_number'];
    }

    /**
     * Sets item_receipt_number
     *
     * @param string|null $item_receipt_number Human-readable identifier refers to the receipt the linked item was billed. </br> Displayed only if item is billed with another receipt. </br> In case of receiptType * **PURCHASE** - **receiptNumber of purchase receipt**.</br> If this field is not present, you will find information in receipt.receiptNumber * **REFUND** - **receiptNumber of purchase receipt**. </br> If this field is not present ,you will find information in receipt.linkedReceiptNumber
     *
     * @return self
     */
    public function setItemReceiptNumber($item_receipt_number)
    {
        if (is_null($item_receipt_number)) {
            throw new \InvalidArgumentException('non-nullable item_receipt_number cannot be null');
        }
        $this->container['item_receipt_number'] = $item_receipt_number;

        return $this;
    }

    /**
     * Gets item_partner_name
     *
     * @return string|null
     */
    public function getItemPartnerName()
    {
        return $this->container['item_partner_name'];
    }

    /**
     * Sets item_partner_name
     *
     * @param string|null $item_partner_name Name of the partner who sold the linked item. </br>Displayed only if the partner is different from partner of the receipt
     *
     * @return self
     */
    public function setItemPartnerName($item_partner_name)
    {
        if (is_null($item_partner_name)) {
            throw new \InvalidArgumentException('non-nullable item_partner_name cannot be null');
        }
        $this->container['item_partner_name'] = $item_partner_name;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string|null
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string|null $sku Stock keeping unit of the linked item. Unique item identifier on partner side </br>This information is not reliably provided for older receipts.
     *
     * @return self
     */
    public function setSku($sku)
    {
        if (is_null($sku)) {
            throw new \InvalidArgumentException('non-nullable sku cannot be null');
        }
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets article_number
     *
     * @return string
     */
    public function getArticleNumber()
    {
        return $this->container['article_number'];
    }

    /**
     * Sets article_number
     *
     * @param string $article_number Unique Identifier of linked item the customer knows from order process.  ATTENTION: Different from the previous version, the field also contains the promotion. In last version the promotion was provided separately
     *
     * @return self
     */
    public function setArticleNumber($article_number)
    {
        if (is_null($article_number)) {
            throw new \InvalidArgumentException('non-nullable article_number cannot be null');
        }
        $this->container['article_number'] = $article_number;

        return $this;
    }

    /**
     * Gets product_title
     *
     * @return string
     */
    public function getProductTitle()
    {
        return $this->container['product_title'];
    }

    /**
     * Sets product_title
     *
     * @param string $product_title Product description of linked item the customer knows from the order process
     *
     * @return self
     */
    public function setProductTitle($product_title)
    {
        if (is_null($product_title)) {
            throw new \InvalidArgumentException('non-nullable product_title cannot be null');
        }
        $this->container['product_title'] = $product_title;

        return $this;
    }

    /**
     * Gets service_relations
     *
     * @return \Otto\Client\Model\ServiceRelationReceiptsV3[]
     */
    public function getServiceRelations()
    {
        return $this->container['service_relations'];
    }

    /**
     * Sets service_relations
     *
     * @param \Otto\Client\Model\ServiceRelationReceiptsV3[] $service_relations List of ServiceRelation objects. </br>Contains entries if services were sold  together with items otherwise list is empty
     *
     * @return self
     */
    public function setServiceRelations($service_relations)
    {
        if (is_null($service_relations)) {
            throw new \InvalidArgumentException('non-nullable service_relations cannot be null');
        }
        $this->container['service_relations'] = $service_relations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


