<?php
/**
 * PaymentReceiptsV3
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PaymentReceiptsV3 Class Doc Comment
 *
 * @category Class
 * @description Payment details
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentReceiptsV3 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Payment__Receipts-V3';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'payment_provider' => 'string',
        'payment_method' => 'string',
        'installment_count' => 'int',
        'payment_break' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'payment_provider' => null,
        'payment_method' => null,
        'installment_count' => 'int32',
        'payment_break' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'payment_provider' => false,
        'payment_method' => false,
        'installment_count' => false,
        'payment_break' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payment_provider' => 'paymentProvider',
        'payment_method' => 'paymentMethod',
        'installment_count' => 'installmentCount',
        'payment_break' => 'paymentBreak'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payment_provider' => 'setPaymentProvider',
        'payment_method' => 'setPaymentMethod',
        'installment_count' => 'setInstallmentCount',
        'payment_break' => 'setPaymentBreak'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payment_provider' => 'getPaymentProvider',
        'payment_method' => 'getPaymentMethod',
        'installment_count' => 'getInstallmentCount',
        'payment_break' => 'getPaymentBreak'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PAYMENT_PROVIDER_PLAZA = 'PLAZA';
    public const PAYMENT_PROVIDER_OTTOPAYMENTS = 'OTTOPAYMENTS';
    public const PAYMENT_METHOD_CREDIT_CARD_ONLINE = 'CREDIT_CARD_ONLINE';
    public const PAYMENT_METHOD_INVOICE_SINGLE = 'INVOICE_SINGLE';
    public const PAYMENT_METHOD_INVOICE_INSTALLMENTS = 'INVOICE_INSTALLMENTS';
    public const PAYMENT_METHOD_DIRECT_DEBIT_INSTALLMENTS = 'DIRECT_DEBIT_INSTALLMENTS';
    public const PAYMENT_METHOD_PREPAYMENT = 'PREPAYMENT';
    public const PAYMENT_METHOD_PAYPAL = 'PAYPAL';
    public const PAYMENT_METHOD_DIRECT_DEBIT = 'DIRECT_DEBIT';
    public const PAYMENT_METHOD_CREDIT_CARD = 'CREDIT_CARD';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPaymentProviderAllowableValues()
    {
        return [
            self::PAYMENT_PROVIDER_PLAZA,
            self::PAYMENT_PROVIDER_OTTOPAYMENTS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPaymentMethodAllowableValues()
    {
        return [
            self::PAYMENT_METHOD_CREDIT_CARD_ONLINE,
            self::PAYMENT_METHOD_INVOICE_SINGLE,
            self::PAYMENT_METHOD_INVOICE_INSTALLMENTS,
            self::PAYMENT_METHOD_DIRECT_DEBIT_INSTALLMENTS,
            self::PAYMENT_METHOD_PREPAYMENT,
            self::PAYMENT_METHOD_PAYPAL,
            self::PAYMENT_METHOD_DIRECT_DEBIT,
            self::PAYMENT_METHOD_CREDIT_CARD,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('payment_provider', $data ?? [], null);
        $this->setIfExists('payment_method', $data ?? [], null);
        $this->setIfExists('installment_count', $data ?? [], null);
        $this->setIfExists('payment_break', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['payment_provider'] === null) {
            $invalidProperties[] = "'payment_provider' can't be null";
        }
        $allowedValues = $this->getPaymentProviderAllowableValues();
        if (!is_null($this->container['payment_provider']) && !in_array($this->container['payment_provider'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'payment_provider', must be one of '%s'",
                $this->container['payment_provider'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['payment_method'] === null) {
            $invalidProperties[] = "'payment_method' can't be null";
        }
        $allowedValues = $this->getPaymentMethodAllowableValues();
        if (!is_null($this->container['payment_method']) && !in_array($this->container['payment_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'payment_method', must be one of '%s'",
                $this->container['payment_method'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payment_provider
     *
     * @return string
     */
    public function getPaymentProvider()
    {
        return $this->container['payment_provider'];
    }

    /**
     * Sets payment_provider
     *
     * @param string $payment_provider Payment Provider chosen for the order. </br> Possible values: * **PLAZA** -  Ratepay * **OTTOPAYMENTS** - OTTO Payments
     *
     * @return self
     */
    public function setPaymentProvider($payment_provider)
    {
        if (is_null($payment_provider)) {
            throw new \InvalidArgumentException('non-nullable payment_provider cannot be null');
        }
        $allowedValues = $this->getPaymentProviderAllowableValues();
        if (!in_array($payment_provider, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'payment_provider', must be one of '%s'",
                    $payment_provider,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['payment_provider'] = $payment_provider;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return string
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param string $payment_method Payment method chosen by the customer to pay for this order.  Possible values: * **INVOICE_SINGLE / INVOICE_INSTALLMENT** - payment on invoice (with or without installments) * **DIRECT_DEBIT / DIRECT_DEBIT_INSTALLMENTS** - payment by direct debit (with or without installments) * **PREPAYMENT** - payment by prepayment * **PAYPAL** - payment by PayPal * **CREDIT_CARD** - payment by credit or debit card  (only applicable for paymentProvider = OTTOPAYMENTS) * **CREDIT_CARD_ONLINE** - payment by credit card  (only applicable for old paymentProvider = PLAZA)
     *
     * @return self
     */
    public function setPaymentMethod($payment_method)
    {
        if (is_null($payment_method)) {
            throw new \InvalidArgumentException('non-nullable payment_method cannot be null');
        }
        $allowedValues = $this->getPaymentMethodAllowableValues();
        if (!in_array($payment_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'payment_method', must be one of '%s'",
                    $payment_method,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['payment_method'] = $payment_method;

        return $this;
    }

    /**
     * Gets installment_count
     *
     * @return int|null
     */
    public function getInstallmentCount()
    {
        return $this->container['installment_count'];
    }

    /**
     * Sets installment_count
     *
     * @param int|null $installment_count For payment methods with installments, this attribute indicates how many installments the customer has chosen when placing the order. </br>Only available on receipts of receiptType PURCHASE. </br>This information is not reliably provided for older receipts
     *
     * @return self
     */
    public function setInstallmentCount($installment_count)
    {
        if (is_null($installment_count)) {
            throw new \InvalidArgumentException('non-nullable installment_count cannot be null');
        }
        $this->container['installment_count'] = $installment_count;

        return $this;
    }

    /**
     * Gets payment_break
     *
     * @return bool|null
     */
    public function getPaymentBreak()
    {
        return $this->container['payment_break'];
    }

    /**
     * Sets payment_break
     *
     * @param bool|null $payment_break The field indicates whether customer has chosen paymentBreak <ul><li>Set to <b>true</b>, if customer has chose paymentBreak</li><li>Set to <b>false</b>, if customer hasn’t chosen paymentBreak</li></ul>
     *
     * @return self
     */
    public function setPaymentBreak($payment_break)
    {
        if (is_null($payment_break)) {
            throw new \InvalidArgumentException('non-nullable payment_break cannot be null');
        }
        $this->container['payment_break'] = $payment_break;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


