<?php
/**
 * PositionItemOrdersV4
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PositionItemOrdersV4 Class Doc Comment
 *
 * @category Class
 * @description PositionItem
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PositionItemOrdersV4 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PositionItem__Orders-V4';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cancellation_date' => '\DateTime',
        'cancellation_reason' => 'string',
        'deal_id' => 'string',
        'deal_name' => 'string',
        'expected_delivery_date' => '\DateTime',
        'fulfillment_status' => 'string',
        'item_value_discount' => '\OpenAPI\Client\Model\AmountOrdersV4',
        'item_value_gross_price' => '\OpenAPI\Client\Model\AmountOrdersV4',
        'item_value_reduced_gross_price' => '\OpenAPI\Client\Model\AmountOrdersV4',
        'position_item_id' => 'string',
        'processable_date' => '\DateTime',
        'product' => '\OpenAPI\Client\Model\ProductOrdersV4',
        'return_accepted_by_marketplace' => 'bool',
        'returned_date' => '\DateTime',
        'sent_date' => '\DateTime',
        'tracking_info' => '\OpenAPI\Client\Model\TrackingInfoOrdersV4',
        'weee_pickup' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'cancellation_date' => 'date-time',
        'cancellation_reason' => null,
        'deal_id' => null,
        'deal_name' => null,
        'expected_delivery_date' => 'date-time',
        'fulfillment_status' => null,
        'item_value_discount' => null,
        'item_value_gross_price' => null,
        'item_value_reduced_gross_price' => null,
        'position_item_id' => null,
        'processable_date' => 'date-time',
        'product' => null,
        'return_accepted_by_marketplace' => null,
        'returned_date' => 'date-time',
        'sent_date' => 'date-time',
        'tracking_info' => null,
        'weee_pickup' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'cancellation_date' => false,
        'cancellation_reason' => false,
        'deal_id' => false,
        'deal_name' => false,
        'expected_delivery_date' => false,
        'fulfillment_status' => false,
        'item_value_discount' => false,
        'item_value_gross_price' => false,
        'item_value_reduced_gross_price' => false,
        'position_item_id' => false,
        'processable_date' => false,
        'product' => false,
        'return_accepted_by_marketplace' => false,
        'returned_date' => false,
        'sent_date' => false,
        'tracking_info' => false,
        'weee_pickup' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cancellation_date' => 'cancellationDate',
        'cancellation_reason' => 'cancellationReason',
        'deal_id' => 'dealId',
        'deal_name' => 'dealName',
        'expected_delivery_date' => 'expectedDeliveryDate',
        'fulfillment_status' => 'fulfillmentStatus',
        'item_value_discount' => 'itemValueDiscount',
        'item_value_gross_price' => 'itemValueGrossPrice',
        'item_value_reduced_gross_price' => 'itemValueReducedGrossPrice',
        'position_item_id' => 'positionItemId',
        'processable_date' => 'processableDate',
        'product' => 'product',
        'return_accepted_by_marketplace' => 'returnAcceptedByMarketplace',
        'returned_date' => 'returnedDate',
        'sent_date' => 'sentDate',
        'tracking_info' => 'trackingInfo',
        'weee_pickup' => 'weeePickup'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cancellation_date' => 'setCancellationDate',
        'cancellation_reason' => 'setCancellationReason',
        'deal_id' => 'setDealId',
        'deal_name' => 'setDealName',
        'expected_delivery_date' => 'setExpectedDeliveryDate',
        'fulfillment_status' => 'setFulfillmentStatus',
        'item_value_discount' => 'setItemValueDiscount',
        'item_value_gross_price' => 'setItemValueGrossPrice',
        'item_value_reduced_gross_price' => 'setItemValueReducedGrossPrice',
        'position_item_id' => 'setPositionItemId',
        'processable_date' => 'setProcessableDate',
        'product' => 'setProduct',
        'return_accepted_by_marketplace' => 'setReturnAcceptedByMarketplace',
        'returned_date' => 'setReturnedDate',
        'sent_date' => 'setSentDate',
        'tracking_info' => 'setTrackingInfo',
        'weee_pickup' => 'setWeeePickup'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cancellation_date' => 'getCancellationDate',
        'cancellation_reason' => 'getCancellationReason',
        'deal_id' => 'getDealId',
        'deal_name' => 'getDealName',
        'expected_delivery_date' => 'getExpectedDeliveryDate',
        'fulfillment_status' => 'getFulfillmentStatus',
        'item_value_discount' => 'getItemValueDiscount',
        'item_value_gross_price' => 'getItemValueGrossPrice',
        'item_value_reduced_gross_price' => 'getItemValueReducedGrossPrice',
        'position_item_id' => 'getPositionItemId',
        'processable_date' => 'getProcessableDate',
        'product' => 'getProduct',
        'return_accepted_by_marketplace' => 'getReturnAcceptedByMarketplace',
        'returned_date' => 'getReturnedDate',
        'sent_date' => 'getSentDate',
        'tracking_info' => 'getTrackingInfo',
        'weee_pickup' => 'getWeeePickup'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CANCELLATION_REASON_CANCELLED_ON_CUSTOMER_WISH = 'CANCELLED_ON_CUSTOMER_WISH';
    public const CANCELLATION_REASON_CANCELLED_ON_PARTNER_WISH = 'CANCELLED_ON_PARTNER_WISH';
    public const CANCELLATION_REASON_PAYMENT_ABORTED = 'PAYMENT_ABORTED';
    public const CANCELLATION_REASON_PAYMENT_FRAUD = 'PAYMENT_FRAUD';
    public const CANCELLATION_REASON_PARTNER_TERMINATED = 'PARTNER_TERMINATED';
    public const CANCELLATION_REASON_ILLEGAL_PRODUCT = 'ILLEGAL_PRODUCT';
    public const CANCELLATION_REASON_MARKETPLACE_FRAUD = 'MARKETPLACE_FRAUD';
    public const CANCELLATION_REASON_CANCELLED_ON_MARKETPLACE_WISH = 'CANCELLED_ON_MARKETPLACE_WISH';
    public const FULFILLMENT_STATUS_ANNOUNCED = 'ANNOUNCED';
    public const FULFILLMENT_STATUS_PROCESSABLE = 'PROCESSABLE';
    public const FULFILLMENT_STATUS_SENT = 'SENT';
    public const FULFILLMENT_STATUS_RETURNED = 'RETURNED';
    public const FULFILLMENT_STATUS_CANCELLED_BY_PARTNER = 'CANCELLED_BY_PARTNER';
    public const FULFILLMENT_STATUS_CANCELLED_BY_MARKETPLACE = 'CANCELLED_BY_MARKETPLACE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCancellationReasonAllowableValues()
    {
        return [
            self::CANCELLATION_REASON_CANCELLED_ON_CUSTOMER_WISH,
            self::CANCELLATION_REASON_CANCELLED_ON_PARTNER_WISH,
            self::CANCELLATION_REASON_PAYMENT_ABORTED,
            self::CANCELLATION_REASON_PAYMENT_FRAUD,
            self::CANCELLATION_REASON_PARTNER_TERMINATED,
            self::CANCELLATION_REASON_ILLEGAL_PRODUCT,
            self::CANCELLATION_REASON_MARKETPLACE_FRAUD,
            self::CANCELLATION_REASON_CANCELLED_ON_MARKETPLACE_WISH,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFulfillmentStatusAllowableValues()
    {
        return [
            self::FULFILLMENT_STATUS_ANNOUNCED,
            self::FULFILLMENT_STATUS_PROCESSABLE,
            self::FULFILLMENT_STATUS_SENT,
            self::FULFILLMENT_STATUS_RETURNED,
            self::FULFILLMENT_STATUS_CANCELLED_BY_PARTNER,
            self::FULFILLMENT_STATUS_CANCELLED_BY_MARKETPLACE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('cancellation_date', $data ?? [], null);
        $this->setIfExists('cancellation_reason', $data ?? [], null);
        $this->setIfExists('deal_id', $data ?? [], null);
        $this->setIfExists('deal_name', $data ?? [], null);
        $this->setIfExists('expected_delivery_date', $data ?? [], null);
        $this->setIfExists('fulfillment_status', $data ?? [], null);
        $this->setIfExists('item_value_discount', $data ?? [], null);
        $this->setIfExists('item_value_gross_price', $data ?? [], null);
        $this->setIfExists('item_value_reduced_gross_price', $data ?? [], null);
        $this->setIfExists('position_item_id', $data ?? [], null);
        $this->setIfExists('processable_date', $data ?? [], null);
        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('return_accepted_by_marketplace', $data ?? [], null);
        $this->setIfExists('returned_date', $data ?? [], null);
        $this->setIfExists('sent_date', $data ?? [], null);
        $this->setIfExists('tracking_info', $data ?? [], null);
        $this->setIfExists('weee_pickup', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCancellationReasonAllowableValues();
        if (!is_null($this->container['cancellation_reason']) && !in_array($this->container['cancellation_reason'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'cancellation_reason', must be one of '%s'",
                $this->container['cancellation_reason'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['fulfillment_status'] === null) {
            $invalidProperties[] = "'fulfillment_status' can't be null";
        }
        $allowedValues = $this->getFulfillmentStatusAllowableValues();
        if (!is_null($this->container['fulfillment_status']) && !in_array($this->container['fulfillment_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fulfillment_status', must be one of '%s'",
                $this->container['fulfillment_status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['item_value_gross_price'] === null) {
            $invalidProperties[] = "'item_value_gross_price' can't be null";
        }
        if ($this->container['position_item_id'] === null) {
            $invalidProperties[] = "'position_item_id' can't be null";
        }
        if ($this->container['product'] === null) {
            $invalidProperties[] = "'product' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cancellation_date
     *
     * @return \DateTime|null
     */
    public function getCancellationDate()
    {
        return $this->container['cancellation_date'];
    }

    /**
     * Sets cancellation_date
     *
     * @param \DateTime|null $cancellation_date Date the position item was cancelled
     *
     * @return self
     */
    public function setCancellationDate($cancellation_date)
    {
        if (is_null($cancellation_date)) {
            throw new \InvalidArgumentException('non-nullable cancellation_date cannot be null');
        }
        $this->container['cancellation_date'] = $cancellation_date;

        return $this;
    }

    /**
     * Gets cancellation_reason
     *
     * @return string|null
     */
    public function getCancellationReason()
    {
        return $this->container['cancellation_reason'];
    }

    /**
     * Sets cancellation_reason
     *
     * @param string|null $cancellation_reason Reason why a position was cancelled
     *
     * @return self
     */
    public function setCancellationReason($cancellation_reason)
    {
        if (is_null($cancellation_reason)) {
            throw new \InvalidArgumentException('non-nullable cancellation_reason cannot be null');
        }
        $allowedValues = $this->getCancellationReasonAllowableValues();
        if (!in_array($cancellation_reason, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'cancellation_reason', must be one of '%s'",
                    $cancellation_reason,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['cancellation_reason'] = $cancellation_reason;

        return $this;
    }

    /**
     * Gets deal_id
     *
     * @return string|null
     */
    public function getDealId()
    {
        return $this->container['deal_id'];
    }

    /**
     * Sets deal_id
     *
     * @param string|null $deal_id The unique id of the deal related to the position item
     *
     * @return self
     */
    public function setDealId($deal_id)
    {
        if (is_null($deal_id)) {
            throw new \InvalidArgumentException('non-nullable deal_id cannot be null');
        }
        $this->container['deal_id'] = $deal_id;

        return $this;
    }

    /**
     * Gets deal_name
     *
     * @return string|null
     */
    public function getDealName()
    {
        return $this->container['deal_name'];
    }

    /**
     * Sets deal_name
     *
     * @param string|null $deal_name The name of the deal related to the position item
     *
     * @return self
     */
    public function setDealName($deal_name)
    {
        if (is_null($deal_name)) {
            throw new \InvalidArgumentException('non-nullable deal_name cannot be null');
        }
        $this->container['deal_name'] = $deal_name;

        return $this;
    }

    /**
     * Gets expected_delivery_date
     *
     * @return \DateTime|null
     */
    public function getExpectedDeliveryDate()
    {
        return $this->container['expected_delivery_date'];
    }

    /**
     * Sets expected_delivery_date
     *
     * @param \DateTime|null $expected_delivery_date The date the position item should be delivered
     *
     * @return self
     */
    public function setExpectedDeliveryDate($expected_delivery_date)
    {
        if (is_null($expected_delivery_date)) {
            throw new \InvalidArgumentException('non-nullable expected_delivery_date cannot be null');
        }
        $this->container['expected_delivery_date'] = $expected_delivery_date;

        return $this;
    }

    /**
     * Gets fulfillment_status
     *
     * @return string
     */
    public function getFulfillmentStatus()
    {
        return $this->container['fulfillment_status'];
    }

    /**
     * Sets fulfillment_status
     *
     * @param string $fulfillment_status The fulfillment status of the position item
     *
     * @return self
     */
    public function setFulfillmentStatus($fulfillment_status)
    {
        if (is_null($fulfillment_status)) {
            throw new \InvalidArgumentException('non-nullable fulfillment_status cannot be null');
        }
        $allowedValues = $this->getFulfillmentStatusAllowableValues();
        if (!in_array($fulfillment_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fulfillment_status', must be one of '%s'",
                    $fulfillment_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fulfillment_status'] = $fulfillment_status;

        return $this;
    }

    /**
     * Gets item_value_discount
     *
     * @return \OpenAPI\Client\Model\AmountOrdersV4|null
     */
    public function getItemValueDiscount()
    {
        return $this->container['item_value_discount'];
    }

    /**
     * Sets item_value_discount
     *
     * @param \OpenAPI\Client\Model\AmountOrdersV4|null $item_value_discount item_value_discount
     *
     * @return self
     */
    public function setItemValueDiscount($item_value_discount)
    {
        if (is_null($item_value_discount)) {
            throw new \InvalidArgumentException('non-nullable item_value_discount cannot be null');
        }
        $this->container['item_value_discount'] = $item_value_discount;

        return $this;
    }

    /**
     * Gets item_value_gross_price
     *
     * @return \OpenAPI\Client\Model\AmountOrdersV4
     */
    public function getItemValueGrossPrice()
    {
        return $this->container['item_value_gross_price'];
    }

    /**
     * Sets item_value_gross_price
     *
     * @param \OpenAPI\Client\Model\AmountOrdersV4 $item_value_gross_price item_value_gross_price
     *
     * @return self
     */
    public function setItemValueGrossPrice($item_value_gross_price)
    {
        if (is_null($item_value_gross_price)) {
            throw new \InvalidArgumentException('non-nullable item_value_gross_price cannot be null');
        }
        $this->container['item_value_gross_price'] = $item_value_gross_price;

        return $this;
    }

    /**
     * Gets item_value_reduced_gross_price
     *
     * @return \OpenAPI\Client\Model\AmountOrdersV4|null
     */
    public function getItemValueReducedGrossPrice()
    {
        return $this->container['item_value_reduced_gross_price'];
    }

    /**
     * Sets item_value_reduced_gross_price
     *
     * @param \OpenAPI\Client\Model\AmountOrdersV4|null $item_value_reduced_gross_price item_value_reduced_gross_price
     *
     * @return self
     */
    public function setItemValueReducedGrossPrice($item_value_reduced_gross_price)
    {
        if (is_null($item_value_reduced_gross_price)) {
            throw new \InvalidArgumentException('non-nullable item_value_reduced_gross_price cannot be null');
        }
        $this->container['item_value_reduced_gross_price'] = $item_value_reduced_gross_price;

        return $this;
    }

    /**
     * Gets position_item_id
     *
     * @return string
     */
    public function getPositionItemId()
    {
        return $this->container['position_item_id'];
    }

    /**
     * Sets position_item_id
     *
     * @param string $position_item_id The unique id of the position item
     *
     * @return self
     */
    public function setPositionItemId($position_item_id)
    {
        if (is_null($position_item_id)) {
            throw new \InvalidArgumentException('non-nullable position_item_id cannot be null');
        }
        $this->container['position_item_id'] = $position_item_id;

        return $this;
    }

    /**
     * Gets processable_date
     *
     * @return \DateTime|null
     */
    public function getProcessableDate()
    {
        return $this->container['processable_date'];
    }

    /**
     * Sets processable_date
     *
     * @param \DateTime|null $processable_date Date the position item has reached PROCESSABLE fulfillment status
     *
     * @return self
     */
    public function setProcessableDate($processable_date)
    {
        if (is_null($processable_date)) {
            throw new \InvalidArgumentException('non-nullable processable_date cannot be null');
        }
        $this->container['processable_date'] = $processable_date;

        return $this;
    }

    /**
     * Gets product
     *
     * @return \OpenAPI\Client\Model\ProductOrdersV4
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \OpenAPI\Client\Model\ProductOrdersV4 $product product
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets return_accepted_by_marketplace
     *
     * @return bool|null
     */
    public function getReturnAcceptedByMarketplace()
    {
        return $this->container['return_accepted_by_marketplace'];
    }

    /**
     * Sets return_accepted_by_marketplace
     *
     * @param bool|null $return_accepted_by_marketplace Flag to indicate that the return has been accepted by the marketplace
     *
     * @return self
     */
    public function setReturnAcceptedByMarketplace($return_accepted_by_marketplace)
    {
        if (is_null($return_accepted_by_marketplace)) {
            throw new \InvalidArgumentException('non-nullable return_accepted_by_marketplace cannot be null');
        }
        $this->container['return_accepted_by_marketplace'] = $return_accepted_by_marketplace;

        return $this;
    }

    /**
     * Gets returned_date
     *
     * @return \DateTime|null
     */
    public function getReturnedDate()
    {
        return $this->container['returned_date'];
    }

    /**
     * Sets returned_date
     *
     * @param \DateTime|null $returned_date Date the position item was returned
     *
     * @return self
     */
    public function setReturnedDate($returned_date)
    {
        if (is_null($returned_date)) {
            throw new \InvalidArgumentException('non-nullable returned_date cannot be null');
        }
        $this->container['returned_date'] = $returned_date;

        return $this;
    }

    /**
     * Gets sent_date
     *
     * @return \DateTime|null
     */
    public function getSentDate()
    {
        return $this->container['sent_date'];
    }

    /**
     * Sets sent_date
     *
     * @param \DateTime|null $sent_date Date the position item was sent
     *
     * @return self
     */
    public function setSentDate($sent_date)
    {
        if (is_null($sent_date)) {
            throw new \InvalidArgumentException('non-nullable sent_date cannot be null');
        }
        $this->container['sent_date'] = $sent_date;

        return $this;
    }

    /**
     * Gets tracking_info
     *
     * @return \OpenAPI\Client\Model\TrackingInfoOrdersV4|null
     */
    public function getTrackingInfo()
    {
        return $this->container['tracking_info'];
    }

    /**
     * Sets tracking_info
     *
     * @param \OpenAPI\Client\Model\TrackingInfoOrdersV4|null $tracking_info tracking_info
     *
     * @return self
     */
    public function setTrackingInfo($tracking_info)
    {
        if (is_null($tracking_info)) {
            throw new \InvalidArgumentException('non-nullable tracking_info cannot be null');
        }
        $this->container['tracking_info'] = $tracking_info;

        return $this;
    }

    /**
     * Gets weee_pickup
     *
     * @return bool|null
     */
    public function getWeeePickup()
    {
        return $this->container['weee_pickup'];
    }

    /**
     * Sets weee_pickup
     *
     * @param bool|null $weee_pickup Position item has electrical and electronic equipment disposal service (WEEE)
     *
     * @return self
     */
    public function setWeeePickup($weee_pickup)
    {
        if (is_null($weee_pickup)) {
            throw new \InvalidArgumentException('non-nullable weee_pickup cannot be null');
        }
        $this->container['weee_pickup'] = $weee_pickup;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


