<?php
/**
 * ReceiptReceiptsV3
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Otto\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Otto\Client\Model;

use \ArrayAccess;
use \Otto\Client\ObjectSerializer;

/**
 * ReceiptReceiptsV3 Class Doc Comment
 *
 * @category Class
 * @description Collection of all details of a receipt
 * @package  Otto\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ReceiptReceiptsV3 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Receipt__Receipts-V3';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'receipt_type' => 'string',
        'is_real_receipt' => 'bool',
        'receipt_number' => 'string',
        'creation_date' => '\DateTime',
        'fulfillment_date' => '\DateTime',
        'sales_order_id' => 'string',
        'order_number' => 'string',
        'order_date' => '\DateTime',
        'shipment_date' => '\DateTime',
        'shipment' => '\Otto\Client\Model\ShipmentReceiptsV3',
        'linked_receipt_number' => 'string',
        'linked_creation_date' => '\DateTime',
        'payment' => '\Otto\Client\Model\PaymentReceiptsV3',
        'partner' => '\Otto\Client\Model\PartnerReceiptsV3',
        'customer' => '\Otto\Client\Model\CustomerReceiptsV3',
        'delivery_address' => '\Otto\Client\Model\AddressReceiptsV3',
        'line_items' => '\Otto\Client\Model\LineItemsReceiptsV3',
        'totals' => '\Otto\Client\Model\PriceReceiptsV3[]',
        'refund_type' => 'string',
        'partial_refund_type' => 'string',
        'amount_due' => '\Otto\Client\Model\ReceiptReceiptsV3AmountDue',
        'totals_gross_amount' => '\Otto\Client\Model\ReceiptReceiptsV3TotalsGrossAmount',
        'totals_reductions' => '\Otto\Client\Model\TotalsReductionReceiptsV3[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'receipt_type' => null,
        'is_real_receipt' => null,
        'receipt_number' => null,
        'creation_date' => 'date-time',
        'fulfillment_date' => 'date-time',
        'sales_order_id' => null,
        'order_number' => null,
        'order_date' => 'date-time',
        'shipment_date' => 'date-time',
        'shipment' => null,
        'linked_receipt_number' => null,
        'linked_creation_date' => 'date-time',
        'payment' => null,
        'partner' => null,
        'customer' => null,
        'delivery_address' => null,
        'line_items' => null,
        'totals' => null,
        'refund_type' => null,
        'partial_refund_type' => null,
        'amount_due' => null,
        'totals_gross_amount' => null,
        'totals_reductions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'receipt_type' => false,
        'is_real_receipt' => false,
        'receipt_number' => false,
        'creation_date' => false,
        'fulfillment_date' => false,
        'sales_order_id' => false,
        'order_number' => false,
        'order_date' => false,
        'shipment_date' => false,
        'shipment' => false,
        'linked_receipt_number' => false,
        'linked_creation_date' => false,
        'payment' => false,
        'partner' => false,
        'customer' => false,
        'delivery_address' => false,
        'line_items' => false,
        'totals' => false,
        'refund_type' => false,
        'partial_refund_type' => false,
        'amount_due' => false,
        'totals_gross_amount' => false,
        'totals_reductions' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'receipt_type' => 'receiptType',
        'is_real_receipt' => 'isRealReceipt',
        'receipt_number' => 'receiptNumber',
        'creation_date' => 'creationDate',
        'fulfillment_date' => 'fulfillmentDate',
        'sales_order_id' => 'salesOrderId',
        'order_number' => 'orderNumber',
        'order_date' => 'orderDate',
        'shipment_date' => 'shipmentDate',
        'shipment' => 'shipment',
        'linked_receipt_number' => 'linkedReceiptNumber',
        'linked_creation_date' => 'linkedCreationDate',
        'payment' => 'payment',
        'partner' => 'partner',
        'customer' => 'customer',
        'delivery_address' => 'deliveryAddress',
        'line_items' => 'lineItems',
        'totals' => 'totals',
        'refund_type' => 'refundType',
        'partial_refund_type' => 'partialRefundType',
        'amount_due' => 'amountDue',
        'totals_gross_amount' => 'totalsGrossAmount',
        'totals_reductions' => 'totalsReductions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'receipt_type' => 'setReceiptType',
        'is_real_receipt' => 'setIsRealReceipt',
        'receipt_number' => 'setReceiptNumber',
        'creation_date' => 'setCreationDate',
        'fulfillment_date' => 'setFulfillmentDate',
        'sales_order_id' => 'setSalesOrderId',
        'order_number' => 'setOrderNumber',
        'order_date' => 'setOrderDate',
        'shipment_date' => 'setShipmentDate',
        'shipment' => 'setShipment',
        'linked_receipt_number' => 'setLinkedReceiptNumber',
        'linked_creation_date' => 'setLinkedCreationDate',
        'payment' => 'setPayment',
        'partner' => 'setPartner',
        'customer' => 'setCustomer',
        'delivery_address' => 'setDeliveryAddress',
        'line_items' => 'setLineItems',
        'totals' => 'setTotals',
        'refund_type' => 'setRefundType',
        'partial_refund_type' => 'setPartialRefundType',
        'amount_due' => 'setAmountDue',
        'totals_gross_amount' => 'setTotalsGrossAmount',
        'totals_reductions' => 'setTotalsReductions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'receipt_type' => 'getReceiptType',
        'is_real_receipt' => 'getIsRealReceipt',
        'receipt_number' => 'getReceiptNumber',
        'creation_date' => 'getCreationDate',
        'fulfillment_date' => 'getFulfillmentDate',
        'sales_order_id' => 'getSalesOrderId',
        'order_number' => 'getOrderNumber',
        'order_date' => 'getOrderDate',
        'shipment_date' => 'getShipmentDate',
        'shipment' => 'getShipment',
        'linked_receipt_number' => 'getLinkedReceiptNumber',
        'linked_creation_date' => 'getLinkedCreationDate',
        'payment' => 'getPayment',
        'partner' => 'getPartner',
        'customer' => 'getCustomer',
        'delivery_address' => 'getDeliveryAddress',
        'line_items' => 'getLineItems',
        'totals' => 'getTotals',
        'refund_type' => 'getRefundType',
        'partial_refund_type' => 'getPartialRefundType',
        'amount_due' => 'getAmountDue',
        'totals_gross_amount' => 'getTotalsGrossAmount',
        'totals_reductions' => 'getTotalsReductions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const RECEIPT_TYPE_PURCHASE = 'PURCHASE';
    public const RECEIPT_TYPE_REFUND = 'REFUND';
    public const RECEIPT_TYPE_PARTIAL_REFUND = 'PARTIAL_REFUND';
    public const REFUND_TYPE__RETURN = 'RETURN';
    public const REFUND_TYPE_CANCELLATION = 'CANCELLATION';
    public const REFUND_TYPE_SERVICE_FULL_REFUND_CANCELLED_BY_SDU = 'SERVICE_FULL_REFUND_CANCELLED_BY_SDU';
    public const REFUND_TYPE_SERVICE_FULL_REFUND_PRODUCT_RETURNED = 'SERVICE_FULL_REFUND_PRODUCT_RETURNED';
    public const PARTIAL_REFUND_TYPE_REFUND_COMPLAINT_ITEM = 'REFUND_COMPLAINT_ITEM';
    public const PARTIAL_REFUND_TYPE_REFUND_PAYPAL_DISPUTE = 'REFUND_PAYPAL_DISPUTE';
    public const PARTIAL_REFUND_TYPE_REFUND_ESCALATION = 'REFUND_ESCALATION';
    public const PARTIAL_REFUND_TYPE_REFUND_PARTIAL_AMOUNT_AFTER_SERVICE_CANCELLATION = 'REFUND_PARTIAL_AMOUNT_AFTER_SERVICE_CANCELLATION';
    public const PARTIAL_REFUND_TYPE_REFUND_CREDIT_CARD_DISPUTE = 'REFUND_CREDIT_CARD_DISPUTE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getReceiptTypeAllowableValues()
    {
        return [
            self::RECEIPT_TYPE_PURCHASE,
            self::RECEIPT_TYPE_REFUND,
            self::RECEIPT_TYPE_PARTIAL_REFUND,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRefundTypeAllowableValues()
    {
        return [
            self::REFUND_TYPE__RETURN,
            self::REFUND_TYPE_CANCELLATION,
            self::REFUND_TYPE_SERVICE_FULL_REFUND_CANCELLED_BY_SDU,
            self::REFUND_TYPE_SERVICE_FULL_REFUND_PRODUCT_RETURNED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPartialRefundTypeAllowableValues()
    {
        return [
            self::PARTIAL_REFUND_TYPE_REFUND_COMPLAINT_ITEM,
            self::PARTIAL_REFUND_TYPE_REFUND_PAYPAL_DISPUTE,
            self::PARTIAL_REFUND_TYPE_REFUND_ESCALATION,
            self::PARTIAL_REFUND_TYPE_REFUND_PARTIAL_AMOUNT_AFTER_SERVICE_CANCELLATION,
            self::PARTIAL_REFUND_TYPE_REFUND_CREDIT_CARD_DISPUTE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('receipt_type', $data ?? [], null);
        $this->setIfExists('is_real_receipt', $data ?? [], null);
        $this->setIfExists('receipt_number', $data ?? [], null);
        $this->setIfExists('creation_date', $data ?? [], null);
        $this->setIfExists('fulfillment_date', $data ?? [], null);
        $this->setIfExists('sales_order_id', $data ?? [], null);
        $this->setIfExists('order_number', $data ?? [], null);
        $this->setIfExists('order_date', $data ?? [], null);
        $this->setIfExists('shipment_date', $data ?? [], null);
        $this->setIfExists('shipment', $data ?? [], null);
        $this->setIfExists('linked_receipt_number', $data ?? [], null);
        $this->setIfExists('linked_creation_date', $data ?? [], null);
        $this->setIfExists('payment', $data ?? [], null);
        $this->setIfExists('partner', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('delivery_address', $data ?? [], null);
        $this->setIfExists('line_items', $data ?? [], null);
        $this->setIfExists('totals', $data ?? [], null);
        $this->setIfExists('refund_type', $data ?? [], null);
        $this->setIfExists('partial_refund_type', $data ?? [], null);
        $this->setIfExists('amount_due', $data ?? [], null);
        $this->setIfExists('totals_gross_amount', $data ?? [], null);
        $this->setIfExists('totals_reductions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['receipt_type'] === null) {
            $invalidProperties[] = "'receipt_type' can't be null";
        }
        $allowedValues = $this->getReceiptTypeAllowableValues();
        if (!is_null($this->container['receipt_type']) && !in_array($this->container['receipt_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'receipt_type', must be one of '%s'",
                $this->container['receipt_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['is_real_receipt'] === null) {
            $invalidProperties[] = "'is_real_receipt' can't be null";
        }
        if ($this->container['receipt_number'] === null) {
            $invalidProperties[] = "'receipt_number' can't be null";
        }
        if ($this->container['creation_date'] === null) {
            $invalidProperties[] = "'creation_date' can't be null";
        }
        if ($this->container['sales_order_id'] === null) {
            $invalidProperties[] = "'sales_order_id' can't be null";
        }
        if ($this->container['order_number'] === null) {
            $invalidProperties[] = "'order_number' can't be null";
        }
        if ($this->container['order_date'] === null) {
            $invalidProperties[] = "'order_date' can't be null";
        }
        if ($this->container['payment'] === null) {
            $invalidProperties[] = "'payment' can't be null";
        }
        if ($this->container['partner'] === null) {
            $invalidProperties[] = "'partner' can't be null";
        }
        if ($this->container['customer'] === null) {
            $invalidProperties[] = "'customer' can't be null";
        }
        if ($this->container['line_items'] === null) {
            $invalidProperties[] = "'line_items' can't be null";
        }
        if ($this->container['totals'] === null) {
            $invalidProperties[] = "'totals' can't be null";
        }
        $allowedValues = $this->getRefundTypeAllowableValues();
        if (!is_null($this->container['refund_type']) && !in_array($this->container['refund_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'refund_type', must be one of '%s'",
                $this->container['refund_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPartialRefundTypeAllowableValues();
        if (!is_null($this->container['partial_refund_type']) && !in_array($this->container['partial_refund_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'partial_refund_type', must be one of '%s'",
                $this->container['partial_refund_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['amount_due'] === null) {
            $invalidProperties[] = "'amount_due' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets receipt_type
     *
     * @return string
     */
    public function getReceiptType()
    {
        return $this->container['receipt_type'];
    }

    /**
     * Sets receipt_type
     *
     * @param string $receipt_type Categorisation that classifies the receipts according to the main characteristics  ATTENTION: In previous version the information was called type
     *
     * @return self
     */
    public function setReceiptType($receipt_type)
    {
        if (is_null($receipt_type)) {
            throw new \InvalidArgumentException('non-nullable receipt_type cannot be null');
        }
        $allowedValues = $this->getReceiptTypeAllowableValues();
        if (!in_array($receipt_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'receipt_type', must be one of '%s'",
                    $receipt_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['receipt_type'] = $receipt_type;

        return $this;
    }

    /**
     * Gets is_real_receipt
     *
     * @return bool
     */
    public function getIsRealReceipt()
    {
        return $this->container['is_real_receipt'];
    }

    /**
     * Sets is_real_receipt
     *
     * @param bool $is_real_receipt Counterpart to the sentence \"Dies ist kein Beleg/keine Rechnung im Sinne des Umsatzsteuergesetzes und berechtigt nicht zum Vorsteuerabzug.\" on pdf document.    * Set to **true** since real customer invoices/refunds for shipments to locations in domestic tax territory are created.    * Set to **false** for technical receipts not visible to customer or on receipts with delivery addresses on Helgoland or in Büsingen
     *
     * @return self
     */
    public function setIsRealReceipt($is_real_receipt)
    {
        if (is_null($is_real_receipt)) {
            throw new \InvalidArgumentException('non-nullable is_real_receipt cannot be null');
        }
        $this->container['is_real_receipt'] = $is_real_receipt;

        return $this;
    }

    /**
     * Gets receipt_number
     *
     * @return string
     */
    public function getReceiptNumber()
    {
        return $this->container['receipt_number'];
    }

    /**
     * Sets receipt_number
     *
     * @param string $receipt_number Human readable identifier of a receipt known by customer. </br> Guaranteed to be unique per partner
     *
     * @return self
     */
    public function setReceiptNumber($receipt_number)
    {
        if (is_null($receipt_number)) {
            throw new \InvalidArgumentException('non-nullable receipt_number cannot be null');
        }
        $this->container['receipt_number'] = $receipt_number;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return \DateTime
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param \DateTime $creation_date Date when receipt is created by system (UTC in ISO-8601 format)
     *
     * @return self
     */
    public function setCreationDate($creation_date)
    {
        if (is_null($creation_date)) {
            throw new \InvalidArgumentException('non-nullable creation_date cannot be null');
        }
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets fulfillment_date
     *
     * @return \DateTime|null
     */
    public function getFulfillmentDate()
    {
        return $this->container['fulfillment_date'];
    }

    /**
     * Sets fulfillment_date
     *
     * @param \DateTime|null $fulfillment_date Date when service fulfilled.
     *
     * @return self
     */
    public function setFulfillmentDate($fulfillment_date)
    {
        if (is_null($fulfillment_date)) {
            throw new \InvalidArgumentException('non-nullable fulfillment_date cannot be null');
        }
        $this->container['fulfillment_date'] = $fulfillment_date;

        return $this;
    }

    /**
     * Gets sales_order_id
     *
     * @return string
     */
    public function getSalesOrderId()
    {
        return $this->container['sales_order_id'];
    }

    /**
     * Sets sales_order_id
     *
     * @param string $sales_order_id Technical identifier of corresponding sales order
     *
     * @return self
     */
    public function setSalesOrderId($sales_order_id)
    {
        if (is_null($sales_order_id)) {
            throw new \InvalidArgumentException('non-nullable sales_order_id cannot be null');
        }
        $this->container['sales_order_id'] = $sales_order_id;

        return $this;
    }

    /**
     * Gets order_number
     *
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->container['order_number'];
    }

    /**
     * Sets order_number
     *
     * @param string $order_number Order number of corresponding sales order
     *
     * @return self
     */
    public function setOrderNumber($order_number)
    {
        if (is_null($order_number)) {
            throw new \InvalidArgumentException('non-nullable order_number cannot be null');
        }
        $this->container['order_number'] = $order_number;

        return $this;
    }

    /**
     * Gets order_date
     *
     * @return \DateTime
     */
    public function getOrderDate()
    {
        return $this->container['order_date'];
    }

    /**
     * Sets order_date
     *
     * @param \DateTime $order_date Order date of corresponding sales order (UTC in ISO-8601 format)
     *
     * @return self
     */
    public function setOrderDate($order_date)
    {
        if (is_null($order_date)) {
            throw new \InvalidArgumentException('non-nullable order_date cannot be null');
        }
        $this->container['order_date'] = $order_date;

        return $this;
    }

    /**
     * Gets shipment_date
     *
     * @return \DateTime|null
     */
    public function getShipmentDate()
    {
        return $this->container['shipment_date'];
    }

    /**
     * Sets shipment_date
     *
     * @param \DateTime|null $shipment_date Date when physical items of this receipt were handed over to the carrier to be delivered to the customer (UTC in ISO-8601 format).</br>Only available on receipts of receiptType PURCHASE.
     *
     * @return self
     */
    public function setShipmentDate($shipment_date)
    {
        if (is_null($shipment_date)) {
            throw new \InvalidArgumentException('non-nullable shipment_date cannot be null');
        }
        $this->container['shipment_date'] = $shipment_date;

        return $this;
    }

    /**
     * Gets shipment
     *
     * @return \Otto\Client\Model\ShipmentReceiptsV3|null
     */
    public function getShipment()
    {
        return $this->container['shipment'];
    }

    /**
     * Sets shipment
     *
     * @param \Otto\Client\Model\ShipmentReceiptsV3|null $shipment shipment
     *
     * @return self
     */
    public function setShipment($shipment)
    {
        if (is_null($shipment)) {
            throw new \InvalidArgumentException('non-nullable shipment cannot be null');
        }
        $this->container['shipment'] = $shipment;

        return $this;
    }

    /**
     * Gets linked_receipt_number
     *
     * @return string|null
     */
    public function getLinkedReceiptNumber()
    {
        return $this->container['linked_receipt_number'];
    }

    /**
     * Sets linked_receipt_number
     *
     * @param string|null $linked_receipt_number Human-readable identifier of linked receipt.</br> In case of receiptType PARTIAL_REFUND or REFUND it is the receiptINumber of purchase receipt.  ATTENTION: In previous version the information was called originalReceiptNumber
     *
     * @return self
     */
    public function setLinkedReceiptNumber($linked_receipt_number)
    {
        if (is_null($linked_receipt_number)) {
            throw new \InvalidArgumentException('non-nullable linked_receipt_number cannot be null');
        }
        $this->container['linked_receipt_number'] = $linked_receipt_number;

        return $this;
    }

    /**
     * Gets linked_creation_date
     *
     * @return \DateTime|null
     */
    public function getLinkedCreationDate()
    {
        return $this->container['linked_creation_date'];
    }

    /**
     * Sets linked_creation_date
     *
     * @param \DateTime|null $linked_creation_date Creation date of linked receipt (UTC in ISO-8601 format).</br>Only available if there is a linked receipt.  ATTENTION: In previous version the information was called originalCreatedDate
     *
     * @return self
     */
    public function setLinkedCreationDate($linked_creation_date)
    {
        if (is_null($linked_creation_date)) {
            throw new \InvalidArgumentException('non-nullable linked_creation_date cannot be null');
        }
        $this->container['linked_creation_date'] = $linked_creation_date;

        return $this;
    }

    /**
     * Gets payment
     *
     * @return \Otto\Client\Model\PaymentReceiptsV3
     */
    public function getPayment()
    {
        return $this->container['payment'];
    }

    /**
     * Sets payment
     *
     * @param \Otto\Client\Model\PaymentReceiptsV3 $payment payment
     *
     * @return self
     */
    public function setPayment($payment)
    {
        if (is_null($payment)) {
            throw new \InvalidArgumentException('non-nullable payment cannot be null');
        }
        $this->container['payment'] = $payment;

        return $this;
    }

    /**
     * Gets partner
     *
     * @return \Otto\Client\Model\PartnerReceiptsV3
     */
    public function getPartner()
    {
        return $this->container['partner'];
    }

    /**
     * Sets partner
     *
     * @param \Otto\Client\Model\PartnerReceiptsV3 $partner partner
     *
     * @return self
     */
    public function setPartner($partner)
    {
        if (is_null($partner)) {
            throw new \InvalidArgumentException('non-nullable partner cannot be null');
        }
        $this->container['partner'] = $partner;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return \Otto\Client\Model\CustomerReceiptsV3
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \Otto\Client\Model\CustomerReceiptsV3 $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets delivery_address
     *
     * @return \Otto\Client\Model\AddressReceiptsV3|null
     */
    public function getDeliveryAddress()
    {
        return $this->container['delivery_address'];
    }

    /**
     * Sets delivery_address
     *
     * @param \Otto\Client\Model\AddressReceiptsV3|null $delivery_address delivery_address
     *
     * @return self
     */
    public function setDeliveryAddress($delivery_address)
    {
        if (is_null($delivery_address)) {
            throw new \InvalidArgumentException('non-nullable delivery_address cannot be null');
        }
        $this->container['delivery_address'] = $delivery_address;

        return $this;
    }

    /**
     * Gets line_items
     *
     * @return \Otto\Client\Model\LineItemsReceiptsV3
     */
    public function getLineItems()
    {
        return $this->container['line_items'];
    }

    /**
     * Sets line_items
     *
     * @param \Otto\Client\Model\LineItemsReceiptsV3 $line_items line_items
     *
     * @return self
     */
    public function setLineItems($line_items)
    {
        if (is_null($line_items)) {
            throw new \InvalidArgumentException('non-nullable line_items cannot be null');
        }
        $this->container['line_items'] = $line_items;

        return $this;
    }

    /**
     * Gets totals
     *
     * @return \Otto\Client\Model\PriceReceiptsV3[]
     */
    public function getTotals()
    {
        return $this->container['totals'];
    }

    /**
     * Sets totals
     *
     * @param \Otto\Client\Model\PriceReceiptsV3[] $totals Total amounts of receipt per tax type and tax rate
     *
     * @return self
     */
    public function setTotals($totals)
    {
        if (is_null($totals)) {
            throw new \InvalidArgumentException('non-nullable totals cannot be null');
        }
        $this->container['totals'] = $totals;

        return $this;
    }

    /**
     * Gets refund_type
     *
     * @return string|null
     */
    public function getRefundType()
    {
        return $this->container['refund_type'];
    }

    /**
     * Sets refund_type
     *
     * @param string|null $refund_type Field describes the business case of a refund in more detail.    <br/>Only available on receipts of receiptType REFUND and not reliable provided on older partial refund receipts.    The following refundTypes are possible:   * **RETURN** - Refund due to a return of an item   * **CANCELLATION** - Refund of delivery fees due to a cancellation   * **SERVICE_FULL_REFUND_CANCELLED_BY_SDU** - Refund of a service without item   * **SERVICE_FULL_REFUND_PRODUCT_RETURNED** - Refund a service parallel to an item return
     *
     * @return self
     */
    public function setRefundType($refund_type)
    {
        if (is_null($refund_type)) {
            throw new \InvalidArgumentException('non-nullable refund_type cannot be null');
        }
        $allowedValues = $this->getRefundTypeAllowableValues();
        if (!in_array($refund_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'refund_type', must be one of '%s'",
                    $refund_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['refund_type'] = $refund_type;

        return $this;
    }

    /**
     * Gets partial_refund_type
     *
     * @return string|null
     */
    public function getPartialRefundType()
    {
        return $this->container['partial_refund_type'];
    }

    /**
     * Sets partial_refund_type
     *
     * @param string|null $partial_refund_type Business case of partial refund chosen by partner. Has an impact on the business flow and the PDF.                                                                                              </br>Only available on receipts of receiptType PARTIAL_REFUND and not reliable provides on older partial refunds receipts.  Possible values: * **REFUND_COMPLAINT_ITEM** - Refund because of justified customer complaint on item * **REFUND_PAYPAL_DISPUTE** - Partial or full amount of item price was refunded due to a dispute in Paypal payment * **REFUND_ESCALATION** - Partial amount of item price was refunded due to an escalation * **REFUND_PARTIAL_AMOUNT_AFTER_SERVICE_CANCELLATION** - Lowering of service price after service was not fulfilled completely * **REFUND_CREDIT_CARD_DISPUTE** - Partial or full amount of item price was refunded due to a dispute in CREDIT_CARD payment
     *
     * @return self
     */
    public function setPartialRefundType($partial_refund_type)
    {
        if (is_null($partial_refund_type)) {
            throw new \InvalidArgumentException('non-nullable partial_refund_type cannot be null');
        }
        $allowedValues = $this->getPartialRefundTypeAllowableValues();
        if (!in_array($partial_refund_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'partial_refund_type', must be one of '%s'",
                    $partial_refund_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['partial_refund_type'] = $partial_refund_type;

        return $this;
    }

    /**
     * Gets amount_due
     *
     * @return \Otto\Client\Model\ReceiptReceiptsV3AmountDue
     */
    public function getAmountDue()
    {
        return $this->container['amount_due'];
    }

    /**
     * Sets amount_due
     *
     * @param \Otto\Client\Model\ReceiptReceiptsV3AmountDue $amount_due amount_due
     *
     * @return self
     */
    public function setAmountDue($amount_due)
    {
        if (is_null($amount_due)) {
            throw new \InvalidArgumentException('non-nullable amount_due cannot be null');
        }
        $this->container['amount_due'] = $amount_due;

        return $this;
    }

    /**
     * Gets totals_gross_amount
     *
     * @return \Otto\Client\Model\ReceiptReceiptsV3TotalsGrossAmount|null
     */
    public function getTotalsGrossAmount()
    {
        return $this->container['totals_gross_amount'];
    }

    /**
     * Sets totals_gross_amount
     *
     * @param \Otto\Client\Model\ReceiptReceiptsV3TotalsGrossAmount|null $totals_gross_amount totals_gross_amount
     *
     * @return self
     */
    public function setTotalsGrossAmount($totals_gross_amount)
    {
        if (is_null($totals_gross_amount)) {
            throw new \InvalidArgumentException('non-nullable totals_gross_amount cannot be null');
        }
        $this->container['totals_gross_amount'] = $totals_gross_amount;

        return $this;
    }

    /**
     * Gets totals_reductions
     *
     * @return \Otto\Client\Model\TotalsReductionReceiptsV3[]|null
     */
    public function getTotalsReductions()
    {
        return $this->container['totals_reductions'];
    }

    /**
     * Sets totals_reductions
     *
     * @param \Otto\Client\Model\TotalsReductionReceiptsV3[]|null $totals_reductions Reduction amounts on total value of receipts (currently it includes voucher reduction)
     *
     * @return self
     */
    public function setTotalsReductions($totals_reductions)
    {
        if (is_null($totals_reductions)) {
            throw new \InvalidArgumentException('non-nullable totals_reductions cannot be null');
        }
        $this->container['totals_reductions'] = $totals_reductions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


