<?php
/**
 * APIResponsePriceReductionsV1Test
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Otto\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Otto\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * APIResponsePriceReductionsV1Test Class Doc Comment
 *
 * @category    Class
 * @description APIResponsePriceReductionsV1
 * @package     Otto\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class APIResponsePriceReductionsV1Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "APIResponsePriceReductionsV1"
     */
    public function testAPIResponsePriceReductionsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "detail"
     */
    public function testPropertyDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "logref"
     */
    public function testPropertyLogref()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
