<?php
/**
 * AvailabilityV1StoreAvailableQuantitiesUsingPOST401ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Otto\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Otto\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AvailabilityV1StoreAvailableQuantitiesUsingPOST401ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description AvailabilityV1StoreAvailableQuantitiesUsingPOST401Response
 * @package     Otto\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AvailabilityV1StoreAvailableQuantitiesUsingPOST401ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AvailabilityV1StoreAvailableQuantitiesUsingPOST401Response"
     */
    public function testAvailabilityV1StoreAvailableQuantitiesUsingPOST401Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
