<?php
/**
 * ShippingProfilesV1ApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ShippingProfilesV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShippingProfilesV1ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for shippingProfilesV1CreateShippingProfile
     *
     * Create shipping profile.
     *
     */
    public function testShippingProfilesV1CreateShippingProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for shippingProfilesV1DeleteShippingProfile
     *
     * Delete shipping profile.
     *
     */
    public function testShippingProfilesV1DeleteShippingProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for shippingProfilesV1GetShippingProfileById
     *
     * Get shipping profile by shipping profile id.
     *
     */
    public function testShippingProfilesV1GetShippingProfileById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for shippingProfilesV1GetShippingProfiles
     *
     * Get all shipping profiles from a partner.
     *
     */
    public function testShippingProfilesV1GetShippingProfiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for shippingProfilesV1UpdateShippingProfile
     *
     * Update shipping profile.
     *
     */
    public function testShippingProfilesV1UpdateShippingProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
