<?php
/**
 * SponsoredProductAdsReportingV1ApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SponsoredProductAdsReportingV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SponsoredProductAdsReportingV1ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for sponsoredProductAdsReportingV1CreateCampaignPerformanceReportV1SpaReportingCampaignPerformancePost
     *
     * Create Campaign Performance Report.
     *
     */
    public function testSponsoredProductAdsReportingV1CreateCampaignPerformanceReportV1SpaReportingCampaignPerformancePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sponsoredProductAdsReportingV1CreateKeywordPerformanceReportV1SpaReportingKeywordPerformancePost
     *
     * Create Keyword Performance Report.
     *
     */
    public function testSponsoredProductAdsReportingV1CreateKeywordPerformanceReportV1SpaReportingKeywordPerformancePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sponsoredProductAdsReportingV1CreateProductPerformanceReportV1SpaReportingProductPerformancePost
     *
     * Create Product Performance Report.
     *
     */
    public function testSponsoredProductAdsReportingV1CreateProductPerformanceReportV1SpaReportingProductPerformancePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sponsoredProductAdsReportingV1DownloadReportV1SpaReportingReportsDownloadGet
     *
     * Download a report by ID.
     *
     */
    public function testSponsoredProductAdsReportingV1DownloadReportV1SpaReportingReportsDownloadGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sponsoredProductAdsReportingV1GetCampaignPerformanceReportStatusV1SpaReportingCampaignPerformanceStatusGet
     *
     * Get Campaign Performance Report Status.
     *
     */
    public function testSponsoredProductAdsReportingV1GetCampaignPerformanceReportStatusV1SpaReportingCampaignPerformanceStatusGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sponsoredProductAdsReportingV1GetCampaignPerformanceV1SpaReportingCampaignPerformanceGet
     *
     * Get campaign performance with flexible date filtering.
     *
     */
    public function testSponsoredProductAdsReportingV1GetCampaignPerformanceV1SpaReportingCampaignPerformanceGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sponsoredProductAdsReportingV1GetKeywordPerformanceReportStatusV1SpaReportingKeywordPerformanceStatusGet
     *
     * Get Keyword Performance Report Status.
     *
     */
    public function testSponsoredProductAdsReportingV1GetKeywordPerformanceReportStatusV1SpaReportingKeywordPerformanceStatusGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sponsoredProductAdsReportingV1GetProductPerformanceReportStatusV1SpaReportingProductPerformanceStatusGet
     *
     * Get Product Performance Report Status.
     *
     */
    public function testSponsoredProductAdsReportingV1GetProductPerformanceReportStatusV1SpaReportingProductPerformanceStatusGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sponsoredProductAdsReportingV1GetSkuPerformanceV1SpaReportingProductPerformanceGet
     *
     * Get product's performance with flexible date filtering.
     *
     */
    public function testSponsoredProductAdsReportingV1GetSkuPerformanceV1SpaReportingProductPerformanceGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
